### ISSUE TITLE
xDSCWebService needs to detect OS version

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/xPSDesiredStateConfiguration#1]
The provider strings are different between 2012 and 2012 R2

**Comment by hahndorf** [comment]
Can you be a bit more specific where this problem is?

**Comment by mgreenegit** [comment]
It is referenced in the Appendix of the updated Pull Server document (work in progress).  The file type will be different based on how the machine was built.
https://github.com/mgreenegit/Whitepapers/blob/master/PullServerCPIG/PullServerCPIG.md

**Comment by mhendric** [comment]
@mgreenegit , can you comment on if this is still an issue or not? And if so, can you provide some more details on what we need to do to resolve it?

Thanks.

**Comment by mgreenegit** [comment]
We could resolve this but honestly I haven't heard one person reference the this as a complexity since I opened it almost 4 years ago, so I would suggest we close it.

The technical details are here:
https://github.com/mgreenegit/Whitepapers/blob/Dev/PullServerCPIG.md#appendix---understanding-odata-service-data-file-types

@mhendric would you agree we should just close the issue and focus on higher value scenarios?

**Comment by tmeckel** [comment]
The current implementation distinguishes betwenn those two file extensions based on the selected database provider

```PowerShell
"ESENT" {
    $expectedConnectionString = "$DatabasePath\Devices.edb"
}
"System.Data.OleDb" {
    $expectedConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=$DatabasePath\Devices.mdb;"
}
```
Is this sufficient? In the referenced document it's about different server (OS) versions.

**Comment by mgreenegit** [comment]
Yes that solves the issue more directly than by OS.  Thank you.  Closing the issue.
