### ISSUE TITLE
xDscWebService Reporting errors

### ISSUE THREAD

**Issue by gigi81** [PowerShell/xPSDesiredStateConfiguration#106]
I installed the dsc pull server with the xDscWebService resource with this configuration:

xDscWebService PSDSCPullServer 
{ 
	Ensure                  = "Present" 
	EndpointName            = "PSDSCPullServer" 
	Port                    = 8082
	PhysicalPath            = "$env:SystemDrive\inetpub\PSDSCPullServer" 
	CertificateThumbPrint   = "AllowUnencryptedTraffic"
	ModulePath              = "$env:PROGRAMFILES\WindowsPowerShell\DscService\Modules" 
	ConfigurationPath       = "$env:PROGRAMFILES\WindowsPowerShell\DscService\Configuration"             
	State                   = "Started" 
	DependsOn               = "[WindowsFeature]DSCServiceFeature"
	AcceptSelfSignedCertificates = $false
}

The pull part of the service works fine and the clients are able to download the dsc configurations. Anyway they fail to upload the reports with this error:

Job {D0DC432F-FFFE-11E5-80CC-005056B81B83} : 
Http Client 7e00c0e2-9df9-41aa-948b-96b4e8ee771c failed for WebReportManager for configuration The attempt to send status report to the server http://dscserver:8082/PSDSCPullServer.svc/Node(ConfigurationId='7e00c0e2-9df9-41aa-948b-96b4e8ee771c')/SendStatusReport returned unexpected response code BadRequest..

Can someone help me understand why the reports are not sent. Seems like the webservice it's not supporting this call.
Any help would be appreciated.

**Comment by NarineM** [comment]
@gigi81 
In ConfigurationId protocol you need to have 7e00c0e2-9df9-41aa-948b-96b4e8ee771c.mof and its '7e00c0e2-9df9-41aa-948b-96b4e8ee771c.mof.checksum in DSCService\Configuration repository. This is how reporting server authorizes the node for sending status reports.

**Comment by gigi81** [comment]
Hi @Narinem,
The files are there and as I said before they do get downloaded and applied on the client. The part that fail is the reporting back to the compliance server that is the same endpoint as the pull server using the configuration above.

**Comment by Zuldan** [comment]
@gigi81, same issue is at https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/97

Nodes can't report back to the Pull server. This only seems to occur when you use ConfigurationIDs. @NarineM is kindly assisting us with the issue.

**Comment by gigi81** [comment]
Hi @Zuldan,
Sorry I missed that. This is definitely a duplicate of #97. I will close this issue and follow updates there.
