### ISSUE TITLE
xPackage should allow you to specify what hive InstalledCheckRegKey is in

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xPSDesiredStateConfiguration#11]
Since WMF 5 allows you to run as the user, you might be concerned about another hive other than local machine, which is currently hard coded.

**Comment by KarolKaczmarek** [comment]
@TravisEz13 Looks like you have fix ready, are you planning to send PR?

**Comment by TravisEz13** [comment]
already fixed:  https://github.com/PowerShell/xPSDesiredStateConfiguration/commit/c0126f8e7ae96d2c72e3487f2ce99ef5d5b2f0b1
