### ISSUE TITLE
DscService Esent Database Uncontrolled Growth

### ISSUE THREAD

**Issue by gigi81** [PowerShell/xPSDesiredStateConfiguration#113]
Hi,
I created a DSC Pull server and configured 7 client to pull configurations and report to this server.
Other than the problem report here #106, I'm now starting to have an issue with the esent report database growing at a rate of more than 300MB per day. Currently more than 3000 files of 128KB in size named edb**.log are created every day. The clients are configured to check the dsc configuration every 30 minutes.
These are the problems:
1. Why is it logging so much data? And what is this data anyway?
2. How can I delete this data? Is it safe to simply delete the files or can I run a powershell command?
3. Is there a way to reduce the amount of data logged?

**Comment by NarineM** [comment]
@gigi81 
All the transacations history is being stored but you can always delete them. It is safe to just remove the esent files if you no longer need them.

**Comment by gigi81** [comment]
There is also a UserVoice for this issue here:
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13399740-dsc-esent-database-management

**Comment by NarineM** [comment]
Closing since there is already a user voice to track this issue.

**Comment by skest3qc** [comment]
I am having a similar issue. Pullserver is Server 2016 14393.477
I have registered around 80 nodes. I see that after a month of using the server the Devices.edb database is around 1.8GB and also that it takes ages to get a node report for a configuration id.

Code:
    $requestUri = "$serviceURL/Node(ConfigurationId='$ConfigurationId')/StatusReports"

    $request = Invoke-WebRequest -Uri $requestUri  -ContentType "application/json;odata=minimalmetadata;streaming=true;charset=utf-8" `
               -UseBasicParsing -Headers @{Accept = "application/json";ProtocolVersion = "2.0"} `
               -ErrorAction SilentlyContinue -ErrorVariable ev -Verbose: $false
    $object = ConvertFrom-Json $request.content
    return $object.value

I have copied Devices.edb and opened it ESEDDatabaseView and see that there are 65928 rows in StatusReport table.

Is DSC cleaning up the table automatically after some time, or is there a way to delete the rows in the StatusReport table
