### ISSUE TITLE
xRemoteFile failing due to timeout

### ISSUE THREAD

**Issue by asmagin** [PowerShell/xPSDesiredStateConfiguration#120]
I'm trying to download an asset from a server where an initial response is quite long (doing some preparation of big file), but it is not possible to set a timeout for the operation.

Fixed locally by changing the resource scripts:

``` powershell
    try
    {
        Write-Verbose "Downloading $Uri to $DestinationPath"
        Invoke-WebRequest @PSBoundParameters -Headers $headersHashtable -outFile $DestinationPath -TimeoutSec 14400
    }
```

**Comment by PlagueHO** [comment]
I'm planning on doing some work on xRemoteFile so I'll take a look at this one as well.
