### ISSUE TITLE
Request : xPackage errors out on msiexec exit code 3010 (but shouldn't)

### ISSUE THREAD

**Issue by striker24JB** [PowerShell/xPSDesiredStateConfiguration#121]
I was performing an installation and noticed the DSC kept failing because the return code was 3010 instead of 0.

3010 is generated from successful install, but requires reboot.  This appears even if you specify /norestart.

Since 3010 does indicate that the installation succeeded, can we add that value to the returncode list?

**Comment by iainbrighton** [comment]
You can specify what exit codes you think are valid on a per package basis with the ReturnCode[] property. I'm not sure that this should be a default, but open to other people's thoughts..

**Comment by striker24JB** [comment]
Awesome! Can't believe I didn't see that was an available argument.  Worked like a charm.

**Comment by TravisEz13** [comment]
closed per comments
