### ISSUE TITLE
xRemotefile download fails via proxy

### ISSUE THREAD

**Issue by riponbanik** [PowerShell/xPSDesiredStateConfiguration#122]
The original reported issue is in the link below -
https://github.com/puppetlabs/puppetlabs-dsc/issues/160#issuecomment-163691226

In summary, the issue is -
The xRemoteFile DSC Resource is a wrapper around the Invoke-WebRequest cmdlet. Invoke-WebRequest does provide parameters to handle proxy details, however xRemoteFile does not expose parameters itself that uses them. 

What is the environment configuration is required to make it work via proxy. We have tried with http_proxy and https_proxy environment variable set, ie proxy and winhttp proxy.

**Comment by PlagueHO** [comment]
Hi @riponbanik  - This looks like it would be fairly easy to add proxy settings to the resource. I'll schedule some time to have a look at this this week/weekend.

Thanks!

**Comment by riponbanik** [comment]
That would be great. Thanks for looking it after.

**Comment by PlagueHO** [comment]
I'm working on this at the moment. I have to bring the resource up to current standards and guidelines while I'm at it so it'll take a day or two more before it's ready. I'll let you know once it's complete.
