### ISSUE TITLE
Documentation for OData endpoint

### ISSUE THREAD

**Issue by kamranayub** [PowerShell/xPSDesiredStateConfiguration#124]
Is there any documentation for how to use the OData endpoint(s) to get node and status information? The only docs talk about how to retrieve a **single** node's report. Specifically I really just need a way to get ALL nodes currently enrolled in the pull server (and ideally, what configuration they are using), so then I can drill down to specific nodes.

I am using the PSDSCPullServer.svc endpoint as that appears to be the latest OData endpoint.

**Comment by theonlyway** [comment]
I raised a question surrounding this a little while back, It should be covered in #98

**Comment by NarineM** [comment]
@kamranayub 
Enumerating or getting all nodes is currently not supported. For getting specific node status information you can use the msdn documentation : https://msdn.microsoft.com/en-us/powershell/dsc/reportserver
It has some good examples too.

**Comment by kamranayub** [comment]
Be great to know when it will be supported, since the previous compliance
endpoint worked.
