### ISSUE TITLE
MSFT_xDSCWebService: Fix PSSA Issues

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#128]
The PowerShell Script Analyzer issues in MSFT_xDSCWebService need to be fixed.
This is the current result of running Invoke-ScriptAnalyzer:
![image](https://cloud.githubusercontent.com/assets/6372220/15307549/10b62f28-1b89-11e6-8394-3214bb2f678c.png)

**Comment by kwirkykat** [comment]
This is part of #160

**Comment by mhendric** [comment]
This was resolved a while back. Closing.
