### ISSUE TITLE
MSFT_xPackageResource: Fix PSSA Issues

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#131]
The PowerShell Script Analyzer issues in MSFT_xPackageResource need to be fixed.
This is the current result of running Invoke-ScriptAnalyzer:
![image](https://cloud.githubusercontent.com/assets/6372220/15876251/43107fac-2cc1-11e6-929a-c7f3bda688a9.png)
![image](https://cloud.githubusercontent.com/assets/6372220/15876262/502dabf6-2cc1-11e6-997a-b62275c4b933.png)

**Comment by kwirkykat** [comment]
The error here is fixed in #123

**Comment by kwirkykat** [comment]
This is part of #160

**Comment by PlagueHO** [comment]
I'll work on this one if you like, because I need to get a fix through for #52.

**Comment by PlagueHO** [comment]
I'm working through these and am finding that there is some contention over whether or not the PSUseShouldProcessForStateChangingFunction warning should actually be used:
https://github.com/PowerShell/PSScriptAnalyzer/issues/283

My feeling is that this warning:
1. doesn't make a lot of sense when it is reported in Unit/Integration test code.
2. isn't helpful in the context of DSC Resources
3. is often a false positive

Therefore I would propose that this warning is simply suppressed when it occurs in any Unit or Integration tests in any of these modules.

**Comment by kwirkykat** [comment]
@PlagueHO Yes agreed on that rule. Just posted the [PSSA rule severity list](https://github.com/PowerShell/DscResources/blob/master/PSSARuleSeverities.md) for DSC Resource Kit.
That should help with what rules are allowed to be suppressed/not suppressed.

Haven't implemented this list in tests yet though.
There has been a lot of update to this file since I submitted this issue. Will update the pic above with current PSSA output.

**Comment by PlagueHO** [comment]
@kwirkykat - oh nice! Good idea on the PSSA List.

As for the remaining rules, those are the only ones I've fixed. I noted the suppression of the PSAvoidGlobalVars one too. I'll submit my PR sometime today/tonight.

Thanks for getting back to me so quick. I'll also get some other PRs through for the warnings on the other resources.
