### ISSUE TITLE
MSFT_xProcessResource: Fix PSSA Issues

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#132]
The PowerShell Script Analyzer issues in MSFT_xProcessResource need to be fixed.
This is the current result of running Invoke-ScriptAnalyzer:
![image](https://cloud.githubusercontent.com/assets/6372220/15307648/f5716452-1b89-11e6-82cf-cfe4bb9856ac.png)
![image](https://cloud.githubusercontent.com/assets/6372220/15307654/029bcb04-1b8a-11e6-9a45-2dbd08eef8f7.png)

**Comment by kwirkykat** [comment]
This is part of #160

**Comment by Dan1el42** [comment]
PR #206 submitted to resolve this issue.
