### ISSUE TITLE
MSFT_xPSSessionConfiguration: Fix PSSA Issues

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#133]
The PowerShell Script Analyzer issues in MSFT_xPSSessionConfiguration need to be fixed.
This is the current result of running Invoke-ScriptAnalyzer:
![image](https://cloud.githubusercontent.com/assets/6372220/15307675/3e533704-1b8a-11e6-88a4-b1a71a724547.png)

**Comment by kwirkykat** [comment]
This is part of #160

**Comment by Dan1el42** [comment]
I am in the process of fixing the PSSA and style issues of this resource. Should be able to submit a PR soon.

**Comment by Dan1el42** [comment]
PR #208 submitted.

**Comment by johlju** [comment]
Closing this as this was merged in PR #208.
