### ISSUE TITLE
MSFT_xRegistryResource: Fix PSSA Issues

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#134]
The PowerShell Script Analyzer issues in MSFT_xRegistryResource need to be fixed.
This is the current result of running Invoke-ScriptAnalyzer:
![image](https://cloud.githubusercontent.com/assets/6372220/15307694/7f05b286-1b8a-11e6-9d17-d5c5c71502a0.png)

**Comment by kwirkykat** [comment]
This is part of #160

**Comment by Dan1el42** [comment]
FYI, I am in the process of fixing the PSSA and style issues for this resource. PR following soon.

**Comment by Dan1el42** [comment]
PR #207 submitted.
