### ISSUE TITLE
MSFT_xWindowsOptionalFeature: Fix PSSA Issues

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#137]
The PowerShell Script Analyzer issues in MSFT_xWindowsOptionalFeature need to be fixed.
This is the current result of running Invoke-ScriptAnalyzer:
![image](https://cloud.githubusercontent.com/assets/6372220/15307741/ff2b5c2c-1b8a-11e6-98a5-49ab0d9c4c9a.png)

**Comment by kwirkykat** [comment]
This is part of #160

**Comment by Dan1el42** [comment]
I'm almost ready to submit a PR for this. Beside the fixes for the PSSA issues I've added an example, an integration test, updated the unit test and fixed long lines.

![image](https://cloud.githubusercontent.com/assets/7493263/17693392/da44fbf8-63c8-11e6-94c8-abb54f0919d4.png)

**Comment by Dan1el42** [comment]
PR #198 submitted. AppVeyor build is green on my account (https://ci.appveyor.com/project/Dan1el42/xpsdesiredstateconfiguration/build/3.13.15.0)
