### ISSUE TITLE
xGroup Throws Error When Using Invoke-DscResource

### ISSUE THREAD

**Issue by PrahlM93** [PowerShell/xPSDesiredStateConfiguration#139]
Hello,
When running Invoke-DscResource on xGroup when specifying a domain account to include as a member, I get an error stating "You cannot call a method on a null-valued expression". This issue doesn't come up when using local accounts only.

Running xGroup with these same parameters in a compiled MOF file presents no problems, but this issue prevents Chef users from using this resource.

Output:
```
PS C:\Users\vagrant> Invoke-DscResource -Method Test -Name 'xGroup' -Property @{Ensure = 'Present'; GroupName = 'S-1-5-32-544'; Credential = $creds; MembersToInclude = @('Dev\Domain Admins')} -ModuleName xPsDesiredStateConfiguration
Invoke-DscResource : You cannot call a method on a null-valued expression.
At line:1 char:1
+ Invoke-DscResource -Method Test -Name 'xGroup' -Property @{Ensure = ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-DscResource], CimException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Microsoft.PowerShell.DesiredStateConfiguration.Commands.InvokeDscReso
   urceMethodCommand

Invoke-DscResource : The PowerShell DSC resource '[xGroup]DirectResourceAccess' with SourceInfo '' threw one or more
non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
At line:1 char:1
+ Invoke-DscResource -Method Test -Name 'xGroup' -Property @{Ensure = ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [Invoke-DscResource], CimEx
   ception
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider,Microsoft.PowerShell.DesiredStateConfiguration.Commands.
   InvokeDscResourceMethodCommand
```

**Comment by PlagueHO** [comment]
I'm just looking into this one at the moment. This particular resource doesn't contain any Unit or Integration tests and needs a bit of work (lots of violations of style guidelines) -so any changes should include work on these issues. I'll try and put some work into it over the next few weeks.

**Comment by PlagueHO** [comment]
After some investigation, the error appears to be occurring in this line:
https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1#L803

This is because $PrincipalContext.ConnectedServer is null in this situation. I'm certain why this is yet, but thought I'd document it now.

**Comment by PlagueHO** [comment]
Some further information on this: The issue only occurs if the account that is being used to call ```Invoke-DSCResource``` (e.g. $creds) is not a member of the domain that the account being added is a member of.

**Comment by PrahlM93** [comment]
@PlagueHO, nice find. Thank you for looking into it.

**Comment by PlagueHO** [comment]
@PrahlM93 - no worries! I'll get onto submitting a PR for this as well as bringing the resource up to standards later on this week.

**Comment by kwirkykat** [comment]
Some tests will be added as part of #160

**Comment by iainbrighton** [comment]
@PlagueHO @PrahlM93 Good find! That change seems to fix the ability to add domain accounts to local groups for me.

**Comment by PlagueHO** [comment]
@iainbrighton - Awesome! I'll get onto this tomorrow now that I've finished the xADComputer ODJ one.

**Comment by PlagueHO** [comment]
@kwirkykat - If I add this fix now without creating unit tests, with the understanding that some tests will be added in #160, will the PR be accepted? I can write unit tests for xGroup, but I don't want to conflict with what you're implementing.

**Comment by kwirkykat** [comment]
@PlagueHO Yes you can submit the PR now without the tests

**Comment by PlagueHO** [comment]
Thanks @kwirkykat  - I'll submit it this weekend. Cheers!

**Comment by PlagueHO** [comment]
Still working on this. I got side tracked. Will try and submit the pr over the next couple of days.

**Comment by PlagueHO** [comment]
Just an update on this: The most recent code commits changed the https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.psm1 significantly. The bug still exists though, so I've got to rework my original fix (the code I originally proposed changing no longer exists).
