### ISSUE TITLE
xService throws error when service already exists

### ISSUE THREAD

**Issue by adweigert** [PowerShell/xPSDesiredStateConfiguration#14]
When the Path property is provided the DSC resource throws an error if the service exists instead of returning true for Test-TargetResource or continuing with the WriteWriteProperties calls for Set-TargetResource. The Path property will always be present in the configuration.

**Comment by alc6379** [comment]
Any ETA on this being included in the dev branch? Alternatively, I could just pull down this change and merge in myself locally if @mgr32 is confident that it works.

**Comment by KarolKaczmarek** [comment]
It's already available in the dev branch, https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/36 has been merged. 
Closing this issue, but feel free to reopen if you have further questions.

**Comment by alc6379** [comment]
Awesome!
