### ISSUE TITLE
Cim Exception in xDSCWebService

### ISSUE THREAD

**Issue by rustyhann** [PowerShell/xPSDesiredStateConfiguration#140]
I receive the following error when applying a pull server configuration on a Server 2016 machine from a Windows 10 machine with WMF 5.0. The error can be created with a PS Session or a CimSession. The temporary solution was to roll back to 3.9.0.0. The calling command is:

Start-DscConfiguration -CimSession $computerName -Path pullServer -Wait -Verbose

Error:

VERBOSE: [SERVER]:                            [[xDSCWebService]PSDSCPullServer] Checking IIS requirements
VERBOSE: [SERVER]:                            [[xDSCWebService]PSDSCPullServer] Delete the App Pool if it exists
VERBOSE: [SERVER]:                            [[xDSCWebService]PSDSCPullServer] Remove the site if it already exists
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a
CommandInfo object.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : BadExpression
    + PSComputerName        : SERVER

The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a
CommandInfo object.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : BadExpression
    + PSComputerName        : SERVER

The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a
CommandInfo object.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : BadExpression
    + PSComputerName        : SERVER

VERBOSE: [SERVER]: LCM:  [ End    Set      ]  [[xDSCWebService]PSDSCPullServer]  in 7.7720 seconds.
The PowerShell DSC resource '[xDSCWebService]PSDSCPullServer' with SourceInfo 'C:\Program
Files\WindowsPowerShell\Modules\CUSTOM\New-DscPullServer.ps1::241::17::xDscWebService' threw one or more non-terminating errors while
running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this
channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : SERVER

VERBOSE: [SERVER]: LCM:  [ Start  Resource ]  [[File]RegistrationKeyFile]

**Comment by SNikalaichyk** [comment]
I can confirm this error. It's reproducible on 3 different server running Windows Server 2012 R2.

**xDSCWebService** fails on first run. An error occurs on an attempt to open the port.
Subsequent attempts are successful. Nevertheless, the port is not opened.

```
VERBOSE: [DSCPULL01]: LCM:  [ Start  Set      ]  [[xDSCWebService]PSDSCPullServer]
VERBOSE: [DSCPULL01]:                            [[xDSCWebService]PSDSCPullServer] Create the IIS endpoint
VERBOSE: [DSCPULL01]:                            [[xDSCWebService]PSDSCPullServer] Setting up endpoint at - http://DSCPULL01:8080/PSDSCPullServer.svc
VERBOSE: [DSCPULL01]:                            [[xDSCWebService]PSDSCPullServer] Checking IIS requirements
VERBOSE: [DSCPULL01]:                            [[xDSCWebService]PSDSCPullServer] Delete the App Pool if it exists
VERBOSE: [DSCPULL01]:                            [[xDSCWebService]PSDSCPullServer] Remove the site if it already exists
The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : BadExpression
    + PSComputerName        : DSCPULL01

The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : BadExpression
    + PSComputerName        : DSCPULL01

The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : BadExpression
    + PSComputerName        : DSCPULL01

VERBOSE: [DSCPULL01]: LCM:  [ End    Set      ]  [[xDSCWebService]PSDSCPullServer]  in 2.6410 seconds.
The PowerShell DSC resource '[xDSCWebService]PSDSCPullServer' with SourceInfo
'C:\Users\SNikalaichyk\Desktop\DscPullServerConfig.ps1::39::9::xDSCWebService' threw one or more non-terminating errors while running the Set-TargetResource functionality.
These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : DSCPULL01

VERBOSE: [DSCPULL01]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : DSCPULL01

```

**Comment by NarineM** [comment]
@rustyhann 
Thanks for reporting this issue. It has been fixed by https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/143
