### ISSUE TITLE
xService Test-Target-Resource return false if no state specified

### ISSUE THREAD

**Issue by gigi81** [PowerShell/xPSDesiredStateConfiguration#141]
I have a dsc xService configuration where I do not specify the "State" parameter.
The service is stopped but I don't really care.
The Test-Target-Resource for the dsc configuration keeps on returning false, unless the service is started.
As long as I never specified the state in the configuration, I expected the test to ignore it and return true.
Am I wrong?

**Comment by iainbrighton** [comment]
@gigi81 No, you're not wrong and this is a bug.

I can only imagine that the initial implementation of this resource was for a particular use case and managing non-started services was not one of them :(. There are lots of instances of this, but we're slowly picking them off!

**Comment by kwirkykat** [comment]
State is currently 'Running' by default in both Set-TargetResource and Test-TargetResource.
You guys are proposing a change to no default?
If so, then yes I agree.

It may be a breaking change for configurations that expect the default though.
Either way please wait until after #159 is merged to make changes to the resource.

**Comment by kwirkykat** [comment]
A way to ignore the state was added in #246. Available in version 5.0.0.0+
