### ISSUE TITLE
Incorrect Database type created on Server 2016 in 3.9.0.0

### ISSUE THREAD

**Issue by rustyhann** [PowerShell/xPSDesiredStateConfiguration#142]
I'm currently using version 3.9.0.0 due to the issue in #140. After successfully creating the Pull Server on a Server 2016 machine, an mdb file is created instead of an edb file. According to #91 the database type is determined by the operating system of the Pull Server. Because the server in question is 2016 an edb database is expected.

The file system after install:

Directory: C:\Program Files\WindowsPowerShell\DscService

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d---s-         6/1/2016   8:02 AM                Configuration
d---s-         6/1/2016   8:02 AM                Modules
-a----         6/1/2016   8:02 AM        1310720 Devices.mdb

The web.config for the endpoint has the appropriate values:

<add key="dbprovider" value="ESENT" />
<add key="dbconnectionstr" value="C:\Program Files\WindowsPowerShell\DscService\Devices.edb" />

**Comment by megamorf** [comment]
The mdb is created either way. The edb will be created when you register your first client.

**Comment by NarineM** [comment]
@rustyhann 
The content of the web.config is the actual type that will be used by your pull server endpoint. The mdb file is always being created. We can look into updating the deployment in such a way it places the mdb file under DSCService folder only when the ole provider is setup in web.config.

**Comment by NarineM** [comment]
@rustyhann 
I have updated the issue description.

**Comment by rustyhann** [comment]
I like the idea of only creating the mdb file only when the OLE provider is used. When I first saw the mdb I was confused (until I read megamorf's post) because I was expecting an edb file.

**Comment by NarineM** [comment]
@rustyhann 
Thanks for reporting this issue. It has been fixed by https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/143. Version 3.11.0.0
