### ISSUE TITLE
xArchive doesn't calculate cache hash code correctly - race condition when multiple archives in one configuration

### ISSUE THREAD

**Issue by chrissimon-au** [PowerShell/xPSDesiredStateConfiguration#16]
Get-CacheEntry calculates a cache key using:

    $key = [string]::Join($args).GetHashCode().ToString()

Unfortuntaely, [string]::Join requires the separator as the first argument, so this will always result in calculating the hash code of the empty string - or 371857150.

If you have multiple archives in the same configuration, they will all get cached to the same key - sometimes this isn't a problem, sometimes it is - it's unpredictable, and seems to depend on random timing of some parallel activities.

The fix is simple:

    $key = [string]::Join(';', $args).GetHashCode().ToString()

**Comment by chrissimon-au** [comment]
Note - the same bug applies to the default "Archive" DSC resource.

**Comment by chrissimon-au** [comment]
See PR #17

**Comment by KarolKaczmarek** [comment]
Fixed by #17
