### ISSUE TITLE
xService Resource Missing Localization Files

### ISSUE THREAD

**Issue by guitarrapc** [PowerShell/xPSDesiredStateConfiguration#168]
Description of issue
----

xService Resource with latest xPSDesiredStateConfiguration (3.11.0) seems couldn't run on non-English OS.

Reason
----

This is because un-comment out ```Import-LocalizedData  LocalizedData -filename MSFT_xServiceResource.strings.psd1``` with this commit.
https://github.com/PowerShell/xPSDesiredStateConfiguration/commit/463376df047e0f46c28e3b9f3e69fd9db5a9fd6a#diff-4b82dc2dcab9c16ff7ca0e0913b1e441R45

Previously this section was comment-out.
https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/12ccf4555dfc358174386f40812678a981654094/DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.psm1#L36

Because xService resource missing localization file, you can see only en-US is included.
https://github.com/PowerShell/xPSDesiredStateConfiguration/tree/12ccf4555dfc358174386f40812678a981654094/DSCResources/MSFT_xServiceResource

![image](https://cloud.githubusercontent.com/assets/3856350/16476686/aba34ecc-3ec4-11e6-91af-1eed9fc4a55e.png)

> only en-US is there.

BTW In-Box PSDesiredStateConfiguration Service Resource never happen this issue as it contains localized file in ```C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration```

![image](https://cloud.githubusercontent.com/assets/3856350/16475676/7044497a-3ebb-11e6-819e-a06e1713cb90.png)

![image](https://cloud.githubusercontent.com/assets/3856350/16475673/6a0b752e-3ebb-11e6-8a89-2761fa90a3bf.png)

How to resolve
----

Add Localization directory for your language, or comment-out while covering languages. 

However add language by user-self means you need to do another work after ```Install-Module xPSDesiredStateConfiguration```, this is too sad. Maybe copy and paste same content of en-US and create all languages folder is much easier :(

![image](https://cloud.githubusercontent.com/assets/3856350/16476675/9a6cddc6-3ec4-11e6-831e-8ea43546e0ce.png)

**Comment by kwirkykat** [comment]
I will re-comment the localization for now and re-release.

**Comment by guitarrapc** [comment]
Thank you for prompt action.
