### ISSUE TITLE
Environment Variable set with xEnvironment Resource could not refer with EnvironmentVariableTarget.Process scope.

### ISSUE THREAD

**Issue by guitarrapc** [PowerShell/xPSDesiredStateConfiguration#172]
## Description

Variables set with xEnvironment Resource can be refer from EnvironmentTarget.Machine Scope as desired but not with EnvironmentTarget.Process Scope.

This issue also happen with In-Box Environment Resource.
## Reproduce Procedure

``` powershell
configuration TestEnvironment
{
    Import-DscResource -ModuleName xPSDesiredStateConfiguration;

    Node localhost
    {
        xEnvironment Test
        {
            Ensure = "Present"
            Name = "TestEnvironment"
            Value = "HOGEMOGE"
            Path = $false
        }
    }
}

TestEnvironment
Start-DscConfiguration -Wait -Force -Verbose -Path .\TestEnvironment
```
### Check EnvironmentTarget.Process

Open New PowerShell or cmd or other process and run following C#/PowerShell to see Environment.

``` powershell
[Environment]::GetEnvironmentVariable("TestEnvironment",[System.EnvironmentVariableTarget]::Process)
```

or 

``` powershell
$env:TestEnvironment
```

or 

``` powershell
ls env:
```
#### Result

nothing will return
### Check EnvironmentTarget.Machine

``` powershell
[Environment]::GetEnvironmentVariable("TestEnvironment",[System.EnvironmentVariableTarget]::Machine)
```
#### Result

Environment Variable `HOGEMOGE` return as expected. 

![image](https://cloud.githubusercontent.com/assets/3856350/16511676/a371b12a-3f8d-11e6-8328-509d0f261c38.png)

![image](https://cloud.githubusercontent.com/assets/3856350/16511688/ca1709ec-3f8d-11e6-9586-c339ce025a4e.png)
### Test-DscConfiguration Result

Fail with first apply

![image](https://cloud.githubusercontent.com/assets/3856350/16511693/df97476e-3f8d-11e6-98c9-d2c926f08c29.png)

Success with second apply with -UseExising

``` powershell
Start-DscConfiguration -Wait -Force -Verbose -UseExisting
```

![image](https://cloud.githubusercontent.com/assets/3856350/16511753/a5a5dda8-3f8e-11e6-8e36-4ac66e895a3b.png)

but still couldn't refer from [System.EnvironmentVariableTarget]::Process.
### Tips

If you open Environment variable GUI and click ok, change will immediately apply to [System.EnvironmentVariableTarget]::Process. (What a strange!)

![image](https://cloud.githubusercontent.com/assets/3856350/16511885/72d413e8-3f90-11e6-933d-5402afbf7e68.png)

Also if you reboot machine, environment variables can be access from [System.EnvironmentVariableTarget]::Process. (Wow)

This issue seems like because of Remote Session? It can reproduce with following.

``` powershell
configuration TestEnvironment
{
    $envKey = "TestEnvironment"
    $envValue = "HOGEMOGE"
    Script TestEnvironment
    {
        SetScript = {
            [Environment]::SetEnvironmentVariable($using:envKey, $using:envValue, [EnvironmentVariableTarget]::Process);
            [Environment]::SetEnvironmentVariable($using:envKey, $using:envValue, [EnvironmentVariableTarget]::Machine);
        }
        TestScript = {
            return ([Environment]::GetEnvironmentVariable($using:envKey, [EnvironmentVariableTarget]::Machine) -eq $using:envValue) -and ([Environment]::GetEnvironmentVariable($using:envKey, [EnvironmentVariableTarget]::Process) -eq $using:envValue)
        }
        GetScript = {
            @{
                GetScript = [Environment]::GetEnvironmentVariable($using:envKey, [EnvironmentVariableTarget]::Machine)
                Result = ([Environment]::GetEnvironmentVariable($using:envKey, [EnvironmentVariableTarget]::Machine) -eq $using:envValue) -and ([Environment]::GetEnvironmentVariable($using:envKey, [EnvironmentVariableTarget]::Process) -eq $using:envValue)
            }
        }
    }
}
```

But issue never happen when locally run following.

``` powershell
[Environment]::SetEnvironmentVariable("TestEnvironment", "HOGEMOGE", [EnvironmentVariableTarget]::Process);
[Environment]::SetEnvironmentVariable("TestEnvironment", "HOGEMOGE", [EnvironmentVariableTarget]::Machine);
```
## What Happen

Any process want to check this environment need to specially target  `[System.EnvironmentVariableTarget]::Machine` scope. I believe  `[System.EnvironmentVariableTarget]::Process` scope is usual usage, like PowerShell does, so it should fix.

**Comment by kwirkykat** [comment]
@guitarrapc This should be fixed in the newest version of xPSDesiredStateConfiguration (6.0.0.0). Can you try it out?

**Comment by guitarrapc** [comment]
Thanks. I will check it.

**Comment by guitarrapc** [comment]
@kwirkykat Tested with 6.0.0.0. Here's result.

Test Code
```powershell
# Test Dsc Configuration Status
Test-DscConfiguration -Detailed

<#
PSComputerName  ResourcesInDesiredState        ResourcesNotInDesiredState     InDesiredState
--------------  -----------------------        --------------------------     --------------
localhost       {[xEnvironment]Test}                                          True
#>

# Process scope
[Environment]::GetEnvironmentVariable("TestEnvironment",[System.EnvironmentVariableTarget]::Process)

<#
# nothing output
#>

# Machine scope
[Environment]::GetEnvironmentVariable("TestEnvironment",[System.EnvironmentVariableTarget]::Machine)

<#
HOGEMOGE
#>
```

Test description | Result
---- | ----
Test-DscConfiguration Result | Fixed
EnvironmentVariableTarget.Process | Still nothing return until reboot or OK on GUI.
EnvironmentVariableTarget.Machine | Success.

**Comment by johlju** [comment]
Closing this as resolved as per previous comment. If this was closed in error then please reopen or comment,

**Comment by JackDDavis** [comment]
Please reopen. This issue seems to be persistent in xEnvironment v8.4.0.0

**Comment by JackDDavis** [comment]
>           Closing this as resolved as per previous comment. If this was closed in error then please reopen or comment,

Please reopen. This issue seems to be persistent in xEnvironment v8.4.0.0
