### ISSUE TITLE
[New Resource] xPSListener

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xPSDesiredStateConfiguration#178]
This would be used to add, remove or configure WS-Man listeners. The most likely use case for this is to allow creation of an HTTPS WS-Man listener and deleting the HTTP WS-Man listener.

I've already created this resource as [cWSManListener](https://github.com/PlagueHO/cWSMan) in a separate resource module and submitted it to be added to the DSC Community resources, but perhaps it would be better to be added to an existing module. I would suggest renaming the resource to xPSListener. Or is there a better suggestion?

In the company I work for we use this resource as well as the xPSDesiredStateConfiguration.xPSEndpoint resource as well as my cWSManListener resource to ensure our remoting connections are secure. It would be really nice if we didn't have to use two resource modules for this task as they're fairly closely related.

**Comment by kwirkykat** [comment]
@PlagueHO Since there's also [this resource](https://github.com/PowerShell/DscResources/issues/156) that you posted, I would say this should be in a separate WSManDsc resource module along with that new resource. 

@TravisEz13 @KarolKaczmarek What do you think?

**Comment by TravisEz13** [comment]
xPSListener doesn't seem like the correct name.

**Comment by PlagueHO** [comment]
@TravisEz13  - I've changed the name of this to:
WSManListener.

Does that sound like a more appropriate name?

**Comment by PlagueHO** [comment]
I'm going to close this issue as it is covered in this Issue:
https://github.com/PowerShell/DscResources/issues/75
