### ISSUE TITLE
xGroup fails on group 'Users'

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xPSDesiredStateConfiguration#180]
Very simple resource:

     Node $NodeName
     {
        xGroup GroupUsers
        {
            Ensure = "Present"
            GroupName = "Users"
        }
     }

In Version `3.12.0.0` this gets me the exception:

`Exception calling ".ctor" with "2" argument(s): "Server names cannot contain a space character."`

Interestingly enough, trying the same with Resource `Group (MSFT_GroupResource)` gives the error:

`Credentials are required to resolve the domain account INTERACTIVE`

this happened on non-Domain machines.

So I can not check whether any user is a member of the `users` group.

**Comment by PlagueHO** [comment]
Hi @hahndorf  - I'm looking into some other issues with this Resource ATM so I'll take a look at this as well.

**Comment by kwirkykat** [comment]
@hahndorf Odd. I can't reproduce this error with xGroup. Added a unit test with an empty group just in case. 
What value did you use for $NodeName? Did that have a space?

@PlagueHO Have you been able to repro this error?

**Comment by PlagueHO** [comment]
@kwirkykat - I haven't looked at this one yet. I'll take a look tomorrow (Saturday) and see if I can replicate.

**Comment by hahndorf** [comment]
What I tried:

New fresh VM 2012 R2

    Install-Module -Name xPSDesiredStateConfiguration

Created a file: userstest.ps1:


     Configuration MyUserConfig
     {

        Import-DscResource –ModuleName 'xPSDesiredStateConfiguration'
        Node "localhost"
        {
              xGroup GroupUsers
              {
                  Ensure = "Present"
                  GroupName = "Users"
              }
        }
     }

     MyUserConfig

then run the script to create the MOF

    .\userstest.ps1

then:

     Start-DscConfiguration -Wait -Verbose -Path .\MyUserConfig

results in:

     Exception calling ".ctor" with "2" argument(s): "Server names cannot contain a
     space character."
         + CategoryInfo          : InvalidOperation: (:) [], CimException
         + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.Power
        Shell.Commands.NewObjectCommand
         + PSComputerName        : localhost

tested on non-AD connected servers. I tried different servers, but they may all have the same underlying  OS base image. I just tried again on my Windows 10 (10586.494) workstation, same error.

**Comment by kwirkykat** [comment]
I see this issue now. Looking into it
