### ISSUE TITLE
Invalid ipmo statement should be import in ResourceDesignerScripts?

### ISSUE THREAD

**Issue by dragon788** [PowerShell/xPSDesiredStateConfiguration#183]
https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/master/ResourceDesignerScripts/New-PSSessionConfigurationResource.ps1

**Comment by kwirkykat** [comment]
ipmo is a valid alias for Import-Module, so the script should still work. Though alias's can change frequently and are not considered stable, so yes this should be changed to Import-Module.
