### ISSUE TITLE
xWindowsOptionalFeature - Running tests creates/updates file in repo

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xPSDesiredStateConfiguration#215]
When running the unit tests for xWindowsOptionalFeature, a log file is created in the root of the repo. The file is called "InstallIncorrectWindowsFeatureLog". It should probably be either:
1. created in the Windows Temp folder (```$ENV:Temp```) and cleaned up after tests are complete.
2. or added to the .gitignore file.

This is a very minor issue and is only a problem if you run tests locally before commiting.

If no one else fixes this I'll get around to it at some point :smile:

**Comment by Dan1el42** [comment]
Thanks @PlagueHO for catching this.

I will submit a PR to fix the unit tests of xWindowsOptionalFeature to create the log file in `$env:TEMP` instead.

**Comment by PlagueHO** [comment]
Awesome! Thanks @Dan1el42 :smile:

**Comment by Dan1el42** [comment]
No worries. PR #217 submitted.
