### ISSUE TITLE
xWebsite error on Windows 7

### ISSUE THREAD

**Issue by rfresow** [PowerShell/xPSDesiredStateConfiguration#219]
xWebsite 1.13 returns an error on Windows 7:

_The command Test-TargetResource of the PS module MSFT_xwebsite does not implement the write property LogPath mentioned in the corresponding MOF schema file C:\Program Files\WindowsPowerShell\Modules\xWebAdministration\DscResources\MSFT_xWebsite\MSFT_xWebsite.schema.mof. All write parameters mentioned in the schema file must be implemented by the command Test-TargetResource._

**Comment by kwirkykat** [comment]
@rfresow  xWebsite is in the [xWebAdministration](https://github.com/PowerShell/xWebAdministration) module. Please open an issue in that repository for this bug.

From the error message it sounds like the version of xWebSite that you have does not have the LogPath parameter implemented correctly.
Can you please include the PowerShell version you are running when you open up the new bug? (Run $PSVersionTable in PowerShell)

@mbreakey3 The code for xWebSite looks correct, but the mof is set up a bit weird.
Could be an issue specific to Windows 7 or an older version of PowerShell.
Please take a look when this comes your way.
