### ISSUE TITLE
xService regression with updating binary path

### ISSUE THREAD

**Issue by CtrlC-Root** [PowerShell/xPSDesiredStateConfiguration#220]
Using `3.11.0.0` and `3.13.0.0` versions of this module you cannot update the binary path of an `xService` resource because it results in the following error:

![dsc_error](https://cloud.githubusercontent.com/assets/4819590/18353640/cdff84fe-75b0-11e6-9843-3d8130a725d7.PNG)

I suspect this is because you can no longer call WMI methods on CIM objects directly in PowerShell which is how I was calling the `Change` method on the `Win32_Service` object in `WriteBinaryProperties`. It seems like at some point after `349f0b74876f9e245a0332f158c14ab2c1cf48d2` the module was changed to use CIM objects but `WriteBinaryProperties` was not updated to match. Does this seem correct or am I misunderstanding the error above?

**Comment by PlagueHO** [comment]
Hi @CtrlC-Root - I'm in the process of getting a large PR accepted for this resource ( #216 ) which does do a rework on some of this code. After that has been merged I'll look at this if it still occurs.

However, I can confirm that the current code does correctly call the Change method on the CIM instance using Invoke-CimMethod. However, changing the service executable path is not a scenario that is being actively tested and I have not seen any code that specifically handles this situation - that does not mean it isn't supported though - just something I've not looked at. But I'll definitely look into this once my PR is through.

**Comment by CtrlC-Root** [comment]
It should be supported, since I got a pull request accepted not too long ago adding support for it. It definitely works in the commit I posted above. It appears that immediately after my pull request was accepted something else was committed that broke it.

**Comment by kwirkykat** [comment]
@CtrlC-Root Something with the resource merge probably broke it :disappointed: 
#216 should be merged before we further investigate this issue though.

**Comment by PlagueHO** [comment]
I'll take a look when I can. At least we can now add regression tests to the repo easily enough to ensure it doesn't break again :smile:

**Comment by PlagueHO** [comment]
Working on this one now. Have replicated and identified the problem.
