### ISSUE TITLE
xPackage: RunAsCredential Parameter Removed

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xPSDesiredStateConfiguration#221]
It appears that in the v3.13.0.0 release, the `RunAsCredential` has been removed. This breaks installations on WMF 4 where the `PsDscRunAsCredential` is not supported :disappointed:.

@kwirkykat is there any particular reason that this has been removed (before I look at adding it back in)?

**Comment by kwirkykat** [comment]
@iainbrighton Sorry :persevere: I messed this up in the resource merge. My bad. ```RunAsCredential``` should be added back to xPackage for WMF 4 support.

I can fix it over this weekend unless someone else can get to it faster.

**Comment by iainbrighton** [comment]
No worries. I'm happy to submit a PR for this as it's impacting us? Not sure I'll get to it over the weekend though!

**Comment by iainbrighton** [comment]
@kwirkykat I'm happy to pick this up with #221 if you want?

**Comment by kwirkykat** [comment]
@iainbrighton Sure. Thanks :smile:
