### ISSUE TITLE
xPackage: Mispelled variable `errLogPath` and inverse conditional (minor)

### ISSUE THREAD

**Issue by kamranayub** [PowerShell/xPSDesiredStateConfiguration#224]
Running into some issues with 3.13.0.0 release:
- [Line 1375](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L1375): errLogPath is mispelled. Should be "errorLogPath"
- [Line 467](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.psm1#L467): The condition is wrong, should be `-ne` because otherwise it is formatting a message with null value.

**Comment by iainbrighton** [comment]
@kwirkykat<https://github.com/kwirkykat> Oops - wrong issue! I'm happy to pick this up with #221<https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/221> if you want?
