### ISSUE TITLE
xService: Add a way to ignore state

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#227]
We need a way to ignore the State in the xService resource.
The current default value of the State parameter is 'Running' which makes it impossible to ignore the state of a service in the configuration as stated in #141.

Removing the default value of 'Running' from the State parameter is not an option as this will break scripts that were previously working. (I don't agree with this, but it has been mandated from on-high.)

I would suggest either adding empty string or 'Ignore' as possible values for the State parameter.
These values would then signify that the configuration should not care what state the service is in.

**Comment by johlju** [comment]
Would `State = 'Any'` be an option instead of `ignore`?

**Comment by kwirkykat** [comment]
@johlju Sure that would work too
@zjalali Is looking at this right now I believe

**Comment by zjalali** [comment]
I believe this is already resolved.
