### ISSUE TITLE
xService: Resource should update when same Path is provided

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#228]
This is probably the same as #126, but I'm creating a new issue for internal tracking.
The issues with #220 probably should also be fixed at the same time.

A service should still update all other properties if the same Path is provided.
Currently, it just writes a verbose message and does not properly update.

**Comment by PlagueHO** [comment]
@kwirkykat - having a look at this one tonight.

**Comment by PlagueHO** [comment]
@kwirkykat  - I've reworked the Set-* and Test-* functions to support these workloads. I've also extended the integration tests to cover these scenarios. I've just got to finish the unit tests but I've run out of time tonight. Will try and finish it tomorrow night.
