### ISSUE TITLE
xDSCWebService has no support for Absent

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xPSDesiredStateConfiguration#23]
As far as I can see, there is no support for removing the Web Services in the MSFT_xDSCWebService resource.

In Test-TargetResource:

        Write-Verbose "Check Ensure"
        if(($Ensure -eq "Present" -and $website -eq $null) -or ($Ensure -eq "Absent" -and $website -ne $null))
        {
            $DesiredConfigurationMatch = $false            
            Write-Verbose "The Website $EndpointName is not present"
            break       
        }

you check for **Absent** and with an existing site `PSDSCPullServer` $DesiredConfigurationMatch will be false, but "The Website $EndpointName is not present" is not correct.

Also in `Set-TargetResource` you don't care about the value of `$Ensure` anymore and always try to create new sites, which fails because there are already there.

It seems to me there is no code for the removal of the files and sites.

**Comment by vors** [comment]
It would be awesome, if you can write [a pester test](https://github.com/pester/Pester) that fails.

**Comment by hahndorf** [comment]
I've written the code to implement Absent, but want to wait for my previous pull request (#25) to go through before bringing this in. I will think about some pester tests.

**Comment by KarolKaczmarek** [comment]
Closed by #30
