### ISSUE TITLE
xUser: Set-LocalUser does not have a 'PasswordChangeableDate' parameter

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xPSDesiredStateConfiguration#236]
There is no parameter 'PasswordChangeableDate' on the function Set-LocalUser.
This parameter is being used at [line 767](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xUserResource/MSFT_xUserResource.psm1#L767) of xUser in the Nano implementation of Set-TargetResource.

It needs to be replaced with a valid way to expire a password on Nano server.

Mariah is already working on this along with other updates to xUser.

**Comment by kwirkykat** [comment]
@mbreakey3 Is this fixed?

**Comment by mbreakey3** [comment]
Yup, it's not in the code anymore
