### ISSUE TITLE
xDscWebService: PSDSCComplianceServer returns HTTP Error 401.2

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xPSDesiredStateConfiguration#24]
When accessing http://localhost:9080/PSDSCComplianceServer.svc in IE I get:

`HTTP Error 401.2 - Unauthorized`

the reason is:

> C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PullServer\PSDSCComplianceServer.config

which is the base for:

> C:\inetpub\PSDSCComplianceServer\web.config

has this node:

        <security>
            <authentication>
                <anonymousAuthentication enabled="false" />
                <basicAuthentication enabled="false" />
                <windowsAuthentication enabled="true" />
            </authentication>
        </security>
        
So only Windows authentication is supported, but my IIS does not have windowsAuthentication installed.

The xDscWebService should check for this and potentially install it:

    dism.exe -online -enable-feature -featurename:IIS-WindowsAuthentication

**Comment by vors** [comment]
:+1:
