### ISSUE TITLE
xRemoteFile unable to use drive created by xStorage/xDisk as Destination in same pass

### ISSUE THREAD

**Issue by HelicalSyncromesh** [PowerShell/xPSDesiredStateConfiguration#248]
Hi, I'm experiencing an issue that is specific to using xRemoteFile in conjunction with xDisk from xStorage module.  I am deploying VMs to Azure which have an additional data disk; my configuration begins with using xDisk to format this disk and assign a drive letter (ex: F:).  Subsequently, I attempt to download a file to F: and receive an error that the drive doesn't exist.  The File resource can use the drive just fine.

This behavior only occurs during the first pass when the drive is created.  When the configuration runs a second time then there is no issue.  However, in Azure Automation / DSC Pull Server scenario this means an additional 15 minutes of waiting for the configuration to be applied a second time.

Here is a script snippet, assume $sourcesPath = "f:\sources"

```
        xWaitforDisk Disk2
        {
            DiskNumber = 2
            RetryIntervalSec = 60
            RetryCount = 60
        }
        xDisk FVolume
        {
            DependsOn = "[xWaitforDisk]Disk2"
            DiskNumber = 2
            DriveLetter = 'F'
            FSLabel = 'SolrZk'
        }
        xWaitforDisk FDisk
        {
            DependsOn = "[xDisk]FVolume"
            DiskNumber = 2
            RetryIntervalSec = 60
            RetryCount = 60
        }
        File DownloadDir
        {
            DependsOn = "[xWaitforDisk]FDisk"
            DestinationPath = $sourcesPath
            Type = "Directory"
            Ensure = "Present"
        }
        xRemoteFile GetSourcesSevenZip
        {
            DependsOn = "[File]DownloadDir"
            DestinationPath = ($sourcesPath+'\'+$sevenzipName)
            Uri = ($blobpath+$sevenzipname)
        }
```

Here is the output. I am copying from pushing Start-DscConfiguration output but the same error occurs also when using Automation Account in Azure.

> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Set      ]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Resource ]  [[xWaitForDisk]Disk2]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Test     ]  [[xWaitForDisk]Disk2]
> VERBOSE: [X8VMR1SOLR1]:                            [[xWaitForDisk]Disk2] Checking for disk '2' ...
> VERBOSE: [X8VMR1SOLR1]:                            [[xWaitForDisk]Disk2] Found disk 'Microsoft Virtual Disk'.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Test     ]  [[xWaitForDisk]Disk2]  in 11.5640 seconds.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Skip   Set      ]  [[xWaitForDisk]Disk2]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Resource ]  [[xWaitForDisk]Disk2]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Resource ]  [[xDisk]FVolume]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Test     ]  [[xDisk]FVolume]
> VERBOSE: [X8VMR1SOLR1]:                            [[xDisk]FVolume] Checking if disk number '2' is initialized...
> VERBOSE: [X8VMR1SOLR1]:                            [[xDisk]FVolume] Disk '2' is initialised with 'RAW' partition style
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Test     ]  [[xDisk]FVolume]  in 0.0620 seconds.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Set      ]  [[xDisk]FVolume]
> VERBOSE: [X8VMR1SOLR1]:                            [[xDisk]FVolume] Checking existing disk partition style...
> VERBOSE: [X8VMR1SOLR1]:                            [[xDisk]FVolume] Initializing disk number '2'...
> VERBOSE: [X8VMR1SOLR1]:                            [[xDisk]FVolume] Creating the partition...
> VERBOSE: [X8VMR1SOLR1]:                            [[xDisk]FVolume] Formatting the volume...
> VERBOSE: [X8VMR1SOLR1]:                            [[xDisk]FVolume] Successfully initialized 'F'.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Set      ]  [[xDisk]FVolume]  in 7.4980 seconds.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Resource ]  [[xDisk]FVolume]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Resource ]  [[xWaitForDisk]FDisk]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Test     ]  [[xWaitForDisk]FDisk]
> VERBOSE: [X8VMR1SOLR1]:                            [[xWaitForDisk]FDisk] Checking for disk '2' ...
> VERBOSE: [X8VMR1SOLR1]:                            [[xWaitForDisk]FDisk] Found disk 'Microsoft Virtual Disk'.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Test     ]  [[xWaitForDisk]FDisk]  in 0.0160 seconds.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Skip   Set      ]  [[xWaitForDisk]FDisk]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Resource ]  [[xWaitForDisk]FDisk]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Resource ]  [[File]DownloadDir]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Test     ]  [[File]DownloadDir]
> VERBOSE: [X8VMR1SOLR1]:                            [[File]DownloadDir] The system cannot find the file specified.
> VERBOSE: [X8VMR1SOLR1]:                            [[File]DownloadDir] The related file/directory is: f:\sources.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Test     ]  [[File]DownloadDir]  in 0.0150 seconds.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Set      ]  [[File]DownloadDir]
> VERBOSE: [X8VMR1SOLR1]:                            [[File]DownloadDir] The system cannot find the file specified.
> VERBOSE: [X8VMR1SOLR1]:                            [[File]DownloadDir] The related file/directory is: f:\sources.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Set      ]  [[File]DownloadDir]  in 0.0000 seconds.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Resource ]  [[File]DownloadDir]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Resource ]  [[xRemoteFile]GetSourcesSevenZip]
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Test     ]  [[xRemoteFile]GetSourcesSevenZip]
> VERBOSE: [X8VMR1SOLR1]:                            [[xRemoteFile]GetSourcesSevenZip] DestinationPath 'f:\sources\7z1602-x64.exe' doesn't exist on the machine.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ End    Test     ]  [[xRemoteFile]GetSourcesSevenZip]  in 0.0320 seconds.
> VERBOSE: [X8VMR1SOLR1]: LCM:  [ Start  Set      ]  [[xRemoteFile]GetSourcesSevenZip]
> Cannot find drive. A drive with the name 'f' does not exist.
>     + CategoryInfo          : ObjectNotFound: (f:) [], CimException
>     + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.NewItemCommand
>     + PSComputerName        : localhost

[File]DownloadDir successfully creates f:\sources but all of my subsequent xRemoteFiles fail to see the drive.

**Comment by PlagueHO** [comment]
Hi @HelicalSyncromesh - that is fairly odd. Especially as a folder can be created on it.

I've submitted a large change to xStorage (it hasn't been merged yet though) that contains a new resource called xWaitForVolume. Once this is in place, could you try adding a step that uses the xWaitForVolume for your F: disk and see if this allows it to work?

Also included in this change are some other improvements to the wait code.

But it is still bizarre that Invoke-WebRequest (which is what xRemoteFile uses) can't access the drive where as New-Item (what File uses).

If I get time I'll try and replicate this problem.

Thanks for the great report BTW.

**Comment by HelicalSyncromesh** [comment]
Hi @PlagueHO, thanks for the reply.  As I continued on this script I found that xRemoteFile is not the only affected Resource.  Turns out Archive suffers the same issue.  I did find a work around that solves the issue for all Resources;  after xDisk I added a Script resource that uses the following for the TestScript:
{ 
Get-PSDrive
Return $true
}

Then I reassigned all of my resources that DependedOn xDisk to DependOn that script instead.  At that point xRemoteFile and Archive were happy and could locate f: on the first pass.

I'm happy to test any changes to xStorage or this so please let me know when your changes merge.

Cheers!
HS

**Comment by PlagueHO** [comment]
Hi @HelicalSyncromesh - actually, this sounds very much like this issue (filed in xStorage):
https://github.com/PowerShell/xStorage/issues/58

@gaelcolas had the same problem (but using xMountImage instead of xDisk) and so we created xWaitForVolume that executes Get-PSDrive until the disk is in a completely ready state. So I'm thinking this resource will solve this problem as well.

However, the PR with this new resource is still under review (https://github.com/PowerShell/xStorage/pull/60). But if you want to you could try out [my fork](https://github.com/PlagueHO/xStorage) of xStorage to see if it resolves the issue - until the PR has been merged and this version has been released properly?

**Comment by johlju** [comment]
@HelicalSyncromesh Did @PlagueHO answer solve your problem, using the WaitForVolume resource in StorageDsc?
