### ISSUE TITLE
xGroup - Error if group contains "NT AUTHORITY" members

### ISSUE THREAD

**Issue by hoppi1804** [PowerShell/xPSDesiredStateConfiguration#250]
If a group that should be modified / monitored by DSC xGroup resource contains a member with "NT AUTHORIY" principal, an exception is thrown.

Repo: 
1. create a local group
2. add members "NT AUTHORIY\SYSTEM" or "NT AUTHORITY\NETWORK SERVICE"
3. create and apply a simple xGroup Configuration to edit the group
(e.g.  xGroup xIisUsrs {
            GroupName = "TestGroup";
            MembersToInclude = "DOMAIN\username";
            PsDscRunAsCredential = $credential;
            Credential = $credential;
        }

Results in:
Exception calling ".ctor" with "4" argument(s): "Server names cannot contain a space character."
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

The error is inside the Get-MembersAsPrincipals function. The member object can not be used to construct a DirectoryEntry
$memberDirectoryEntry = New-Object -TypeName 'System.DirectoryServices.DirectoryEntry' -ArgumentList @( $groupDirectoryMember ) # <-- line 1525 in current master

**Comment by zjalali** [comment]
The failure is actually is `Get-PrincipalContext` function when we want to get a `PrincipalContext` for the current user in the target domain.

**Comment by zjalali** [comment]
This is the status/repro where we see the failure:

```
Add-Type -AssemblyName 'System.DirectoryServices.AccountManagement'
$Scope = "NT AUTHORITY"
$principalContext = New-Object -TypeName 'System.DirectoryServices.AccountManagement.PrincipalContext' -ArgumentList @( [System.DirectoryServices.AccountManagement.ContextType]::Domain, $Scope )
```
