### ISSUE TITLE
Syncing directory structures with File resource and MatchSource + Recurse

### ISSUE THREAD

**Issue by kamranayub** [PowerShell/xPSDesiredStateConfiguration#253]
This is more of a question but to me feels like a bug.

``` powershell
File EnsureDirsAreSynced {
    Ensure = "Present"
    SourcePath = "D:\SOURCE\dir"
    DestinationPath = "D:\TARGET\dir"
    Type = "Directory"
    Recurse = $True
    MatchSource = $True
    Checksum = "SHA-256"
  }
```

I assumed using both the `Recurse = $true` and `MatchSource = $true` of the File resource on a Directory will essentally "sync" the structure of the target directory to the source. But that isn't the case--only new files are added, files that exist in the target that don't exist in the source are not cleaned up.

I can understand this being a safe default. Is there a way to get the behavior I expect? Essentially a "sync" operation from source to target where the target MUST match _exactly_ the source structure. When I see the term "MatchSource" that's what my expectation is. The actual behavior is more of a "MatchAddedOrUpdated".

I can workaround this by adding a File resource that ensures the target is empty beforehand, but I'd like to avoid a "delete everything, then copy" operation where there's even a small amount of time files that _can_ be there are deleted before being returned.

**Comment by kwirkykat** [comment]
@kamranayub Have you tried adding ```Force = $true```?
I think Force is required to delete anything.

**Comment by kamranayub** [comment]
@kwirkykat Yes, I've tried all manner of combinations without success. I think perhaps it may be due to the file caching--i.e. if someone changed a file manually, DSC wouldn't replace it or something like that. I believe it's working better on a fresh VM. So closing for now unless I notice this again.
