### ISSUE TITLE
xDSCWebService - $PhysicalPath default not a good one

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xPSDesiredStateConfiguration#26]
The defaults for the physical path for the two new DSC pull server sites are:

    $env:SystemDrive\inetpub\wwwroot\$EndpointName

which means these files are physically located under the document root of the default web site, that's a bad idea. These files should be separate from each other. I suggest changing the defaults to:

    $env:SystemDrive\inetpub\$EndpointName

**Comment by hahndorf** [comment]
I'm happy to fix this. Do you agree with my suggestion?

**Comment by KarolKaczmarek** [comment]
Thanks! I'll let @rayhayes chime in

**Comment by KarolKaczmarek** [comment]
Closed by #30
