### ISSUE TITLE
Have Compliance reporting endpoint return proper JSON responses for `Errors` and `StatusData`

### ISSUE THREAD

**Issue by kamranayub** [PowerShell/xPSDesiredStateConfiguration#265]
This is annoying. Right now the PSDSCPullServer.svc will return agent job reports that have a `Errors` and `StatusData` parameters as JSON but the JSON is stringified. This means the client needs to implement a special JSON converter to deserialize these properties appropriately. In JSON.NET, I created a custom `ParseAsJsonConverter` but this is sub-optimal. The endpoint should return JSON appropriately.

In that same vein, the `InnerException` property on the DSC exceptions can sometimes be a JSON object (of type Exception) **or** they can be a string. So I have another converter that handles that edge case as well. Be consistent!

It would be awesome to open up the OData service on GH and let us contribute, I'd totally fix these issues myself.

**Comment by johlju** [comment]
If this is not added in the latest Windows Server Pull Server then I'm afraid that this is probably not gonna be resolved. Referencing [Windows Pull Server Planning Update – April 2018](https://blogs.msdn.microsoft.com/powershell/2018/04/19/windows-pull-server-planning-update-april-2018/).

Closing this as not fixed and external.
