### ISSUE TITLE
xPackage: Is it possible to pass a secure parameter to the Arguments value? 

### ISSUE THREAD

**Issue by dawilliams** [PowerShell/xPSDesiredStateConfiguration#266]
Hello,

I'm trying using Azure DSC to pass a encrypted parameter to xpackage like so

azureDeploy.json
```json
"parameters": {
  "appPassword": {
      "type": "securestring",
  },
}
...
"resources": [
{
  "type": "extensions",
  "name": "DSC",
  "apiVersion": "2015-06-15",

  "protectedSettings": {
    "appPassword": "[parameters('appPassword')]",
    "configurationUrlSasToken": "[parameters('_artifactsLocationSasToken')]",
    "artifactsLocationSasToken": "[parameters('_artifactsLocationSasToken')]"
  }
```
configuration.ps1
```powershell
Configuration vm
{
param (
$appPassword,
$artifactsLocationSasToken
)
...
xRemoteFile File
{
  ...
  Uri = "$artifactsLocation/$corePointExe$artifactsLocationSasToken"
}

xPackage app
{
...
Arguments = "/S /v`"/qn ADMIN_USER_PASSWORD=$appPassword`""
}
```
However when I do this, the "ADMIN_USER_PASSWORD" value is not set to parameter.  If I passed the same parameter under settings it works.

**Comment by megamorf** [comment]
Is the missing $ character in your param block a typo?

**Comment by dawilliams** [comment]
@megamorf That was a typo.  Thank you.  I've updated the 1st post with a little more detail.  However, you answered that question.  How do you keep the password out of the mof file?  Thanks.

**Comment by almjohn** [comment]
this is probably a little late but you can use a credential from the automation account that does the provisioning. 

    $domainJoinCreds = Get-AutomationPSCredential -Name 'domainJoinCreds'

This does require you use a configurationData block and that also needs to have allowPlainTextPasswords set. 

write back if you need more details on that its pretty fiddly to get working

**Comment by johlju** [comment]
Closing this issue as there has been to response on this for a long time. If this was closed in error please reopen.
