### ISSUE TITLE
PSWSIISEndpoint.psm1 - Test-IISInstall error

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xPSDesiredStateConfiguration#27]
In:

> \DSCResources\MSFT_xDSCWebService\PSWSIISEndpoint.psm1

line 93:

        $iisVersion = (Get-ItemProperty HKLM:\SOFTWARE\Microsoft\InetStp -ErrorAction silentlycontinue).MajorVersion + (Get-ItemProperty HKLM:\SOFTWARE\Microsoft\InetStp -ErrorAction silentlycontinue).MinorVersion

on 2012 R2: $iisVersion is 13, because the code just adds 8 + 5

luckily there is no older IIS version that adds up to greater than 7, so this code actually works. 

I would recommend just to check the MajorVersion to be less than 7, simpler code is better code.

**Comment by hahndorf** [comment]
I'm happy to fix this

**Comment by KarolKaczmarek** [comment]
Thanks!

**Comment by KarolKaczmarek** [comment]
Closed by #30
