### ISSUE TITLE
Reports Are Empty

### ISSUE THREAD

**Issue by Persistent13** [PowerShell/xPSDesiredStateConfiguration#271]
Hello,

When pulling the report for a node I'm getting nothing in return.

OS: Server 2012 R2
WMF / PowerShell: v5
LCM: v2
PsDesiredStateConfiguration: v1.1
xPsDesiredStateConfiguration: 4.0.0.0
xWebAdministration: 1.14.0.0

The output looks like:
```PowerShell
odata.metadata                                                          value
--------------                                                          -----
https://pull:8080/PSDSCPullServer.svc/$metadata#StatusReport            {}
```

I get nothing returned from browsing to the URL either, just the empty report page.

When I explore the EDB I can see jobs logged in the StatusReport table for all the nodes but I am unable to retrieve the data for any of them.

The Desired State Configuration logs are clean on all the nodes, no errors.

IIS logs show 200 for all requests for the report.

Let me know if there is more information required or what steps I should do to troubleshoot.

**Comment by kwirkykat** [comment]
Maybe this is related to #272?

**Comment by johlju** [comment]
@Persistent13 Is this still a problem for you? If not, did you find a workaround or was there another problem that was solved for this?

**Comment by Persistent13** [comment]
@johlju I'm no longer with the company that this pull server was for and as such no longer have any access to the pull server in question. I can't test any further. You can close this issue.

**Comment by johlju** [comment]
@Persistent13 Thank you for reaching out! Closing this as per previous comment.
