### ISSUE TITLE
xDSCWebService: Adding Firewallrule without checking for existing one.

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xPSDesiredStateConfiguration#28]
As part of the installation of the DSC WebService, the resources adds a new Firewall rule:

> Allow Port 8080 for PSWS

I ran a configuration using that resource a few times and I now have **24** of the above rules, all with the same name.

Before adding this rule the code should check whether it already exists.

**Comment by hahndorf** [comment]
I'm happy to fix this

**Comment by KarolKaczmarek** [comment]
Thanks Peter!

**Comment by KarolKaczmarek** [comment]
Closed by #30
