### ISSUE TITLE
Update Test-IsNanoServer to use reliable method

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xPSDesiredStateConfiguration#282]
The current Test-IsNanoServer function is not using a reliable method of detection of Nano Server.

Please see [this comment](https://github.com/PowerShell/xStorage/pull/70#pullrequestreview-10661354) from @TravisEz13

This is the code we should be using:
```powershell
function Test-IsNanoServer
{
    if(Test-Command -Name Get-ComputerInfo)
    {
        $computerInfo = Get-ComputerInfo

        if("Server" -eq $computerInfo.OsProductType -and "NanoServer" -eq $computerInfo.OsServerLevel)
        {
            return $true
        }
    }         

    return $false
} 
```

**Comment by TravisEz13** [comment]
FYI test-command just tests to see if the command exists and returns true if it exists and false if it does not.
