### ISSUE TITLE
xGroup fails with error "Server names cannot contain a space character”

### ISSUE THREAD

**Issue by cyruszhang** [PowerShell/xPSDesiredStateConfiguration#288]
similar issue here:
https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/180

My config for xGroup:
    [String[]]
    $Members = @('sfcmetrics\dmmadev','redmond\cyrusz', 'redmond\xiaohua')
    xGroup  LocalAdmins
        {
            GroupName = 'Administrators'
            Ensure = 'Present'
            Members = $Members
            Credential = $DomainCreds
            PsDscRunAsCredential = $DomainCreds 
        }

After digging a little, the error happened during call stack:
 Test-TargetResourceOnFullSKU => 
 Get-MembersAsPrincipalsList =>
 Get-PrincipalContext =>
 $principalContext = New-Object -TypeName 'System.DirectoryServices.AccountManagement.PrincipalContext' `
            -ArgumentList @( [System.DirectoryServices.AccountManagement.ContextType]::Domain, $Scope, 
                $principalContextName, $Credential.GetNetworkCredential().Password )

argument list for PrincipalContext ctor:
VERBOSE: [SFCMETRICS]:                            [[xGroup]LocalAdmins] Arg domain [Domain]
VERBOSE: [SFCMETRICS]:                            [[xGroup]LocalAdmins] Arg scope -[NT SERVICE]
VERBOSE: [SFCMETRICS]:                            [[xGroup]LocalAdmins] Arg principalContextName [redmond\cyrusz]
VERBOSE: [SFCMETRICS]:                            [[xGroup]LocalAdmins] Arg password - [***hide***]

API: 
https://msdn.microsoft.com/en-us/library/bb341016(v=vs.110).aspx

So the 2nd parameter - name - is "NT SERVICE" and PrincipalContext does not like it with a space in there.

**Comment by cyruszhang** [comment]
local administrators:

PS E:\>  net localgroup administrators
Alias name     administrators
Comment        Administrators have complete and unrestricted access to the computer/domain

Members

-------------------------------------------------------------------------------
**dmmadev
NT SERVICE\SQLIaaSExtension
REDMOND\Domain Admins**
The command completed successfully.

**Comment by kwirkykat** [comment]
@cyruszhang Can you try this with the new release (6.0.0.0)? There is a fix for NT Service/NT Authority users in that version

**Comment by cyruszhang** [comment]
seems to be working! thanks!

**Comment by andy1547** [comment]
This is still an issue in 6.3.0.0
Trying to add IIS APPPOOL\iHostWSAppPool user to the Administrator group.

Haven't had time to diagnoise the full issue but seems to be thrown in the Get-PrincipalContext function.

Was able to get the desired result with this script resource:
`
Script AddPoolUserToAdministratorGroup{
            GetScript = { @{ Result = '' } }
            SetScript = { Add-LocalGroupMember -Group Administrators -Member 'IIS APPPOOL\mypool') }
            TestScript = {[bool] ((Get-LocalGroupMember -Group Administrators).Name -eq ('IIS APPPOOL\mypool')) } 
        }
`

**Comment by kwirkykat** [comment]
@andy1547 This is a similar issue, though not exactly the same. The previous issue was for the 'NT SERVICE' scope. The question here is should the 'IIS APPPOOL' scope be mapped to the local scope rather than resolved as a domain scope. Right now, this particular scope is not being mapped to the local scope, so the resource is attempting to resolve it as a domain, and domains cannot have spaces to be resolved in this way. We can easily map it to the local scope though if appropriate. Could you possibly provide the SID of IIS APPPOOL so that we can check if this mapping is needed?

**Comment by andy1547** [comment]
@kwirkykat Ok that makes sense.
The SIDs for each application pool are unique per application name so they'd differ on a case by case basis, however each SID is prefixed with S-1-5-82
https://docs.microsoft.com/en-us/iis/manage/configuring-security/application-pool-identities#securing-resources

**Comment by varnav** [comment]
This fails for me with same error:

```
        Group GroupPerflog {
            GroupName        = "Performance Log Users"
            Ensure           = "Present"
            MembersToInclude = @("LogMon", "IIS AppPool\API")
            DependsOn        = @("[xWebAppPool]API")  
        }
```
