### ISSUE TITLE
xDSCWebService - Setup problem when FTP site exists

### ISSUE THREAD

**Issue by hahndorf** [PowerShell/xPSDesiredStateConfiguration#29]
During the setup of the Pull Server sites, all IIS web sites are stopped.

If an FTP site exists on the server or a stopped web site with the same binding as another site, the resource breaks.

Also an attempt is made to stop and start the pool named DefaultAppPool, while this pool exists on a fresh IIS install, it may not be there. (I don't have it on any of my servers anymore)

I'm looking into these issues and try to fix them.

**Comment by hahndorf** [comment]
At the end of `New-PSWSEndpoint` the following is called:

    Update-AllSites start

starting all web sites on the server, even if they were not started before.

This also fails for FTP sites and web sites with duplicate bindings.

Why are all sites stopped and restarted? Why is the DefaultAppPool restarted? Is this really required to add the news DSC pull sites?

To fix these things I need additional logic to remember started sites etc, which I would rather avoid.

**Comment by KarolKaczmarek** [comment]
Closed by #30
