### ISSUE TITLE
xGroup - problem with 'TEST' and local groups

### ISSUE THREAD

**Issue by marcinbojko** [PowerShell/xPSDesiredStateConfiguration#302]
Simple config - create new group and add local Administrators:

```yaml
create_new_group:
  dsc_credential:
    password: password
    user: Administrator
  dsc_groupname: new-group
  dsc_members:
  - Administrators
```
Group is created on first run, local Administrators ARE in in.
On second run we fail 'test stage'.
Whole script:

```powershell
$script:ErrorActionPreference = 'Stop'
$script:WarningPreference     = 'SilentlyContinue'

function new-pscredential
{
  [CmdletBinding()]
  param (
    [parameter(Mandatory=$true,
      ValueFromPipelineByPropertyName=$true)]
    [string]
    $user,

    [parameter(Mandatory=$true,
      ValueFromPipelineByPropertyName=$true)]
    [string]
    $password
  )

  $secpasswd   = ConvertTo-SecureString $password -AsPlainText -Force
  $credentials = New-Object System.Management.Automation.PSCredential ($user, $secpasswd)
  return $credentials
}

$response = @{
  indesiredstate = $false
  rebootrequired = $false
  errormessage   = ''
}

$invokeParams = @{
  Name          = 'Group'
  Method        = 'test'
  Property      = @{
    groupname = 'new-group'
    ensure = 'present'
    members = @('.\Administrators')
    credential = [PSCustomObject]@{'password' = 'password'; 'user' = '.\Administrator'} | new-pscredential
  }
  Verbose =$true
  ModuleName = "PSDesiredStateConfiguration"
}

try{
    $result = Invoke-DscResource @invokeParams
}catch{
  $response.errormessage   = $_.Exception.Message
  return ($response | ConvertTo-Json -Compress)
}

# keep the switch for when Test passes back changed properties
switch ($invokeParams.Method) {
  'Test' {
    $response.indesiredstate = $result.InDesiredState
    return ($response | ConvertTo-Json -Compress)
  }
  'Set' {
    $response.indesiredstate = $true
    $response.rebootrequired = $result.RebootRequired
    return ($response | ConvertTo-Json -Compress)
  }
}
```

_> 
> Invoke-DscResource : Exception calling ".ctor" with "4" argument(s): "The server could not be contacted."
> At C:\Users\marcin.bojko\Documents\xgroup-test.ps1:44 char:15
> +     $result = Invoke-DscResource @invokeParams
> +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Invoke-DscResource], CimException
>     + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand,Microsoft.PowerShell.DesiredStateConfiguration.Comma 
>    nds.InvokeDscResourceMethodCommand
>  
> Invoke-DscResource : The PowerShell DSC resource '[Group]DirectResourceAccess' with SourceInfo '' threw one or more non-terminating errors while running the Test-T
> argetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
> At C:\Users\marcin.bojko\Documents\xgroup-test.ps1:44 char:15
> +     $result = Invoke-DscResource @invokeParams
> +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [Invoke-DscResource], CimException
>     + FullyQualifiedErrorId : NonTerminatingErrorFromProvider,Microsoft.PowerShell.DesiredStateConfiguration.Commands.InvokeDscResourceMethodCommand_

 

> 
> VERBOSE: Performing the operation "Invoke-CimMethod: Resourcetest" on target "MSFT_DSCLocalConfigurationManager".
> VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourcetest,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName
> ' = root/Microsoft/Windows/DesiredStateConfiguration'.
> VERBOSE: An LCM method call arrived from computer W2K12 with user sid S-1-5-21-2614790921-100213042-3806504391-1103.
> VERBOSE: [W2K12]: LCM:  [ Start  Test     ]  [[Group]DirectResourceAccess]  
> VERBOSE: [W2K12]:                            [[Group]DirectResourceAccess] A group with the name new-group exists.
> VERBOSE: [W2K12]:                            [[Group]DirectResourceAccess] Resolving administrators as a local account.
> VERBOSE: [W2K12]: LCM:  [ End    Test     ]  [[Group]DirectResourceAccess] False in 7.3280 seconds.
> VERBOSE: Operation 'Invoke CimMethod' complete.
> {"rebootrequired":false,"indesiredstate":null,"errormessage":""}

Test succeeds, but we get an error and "indesiretstate" returns null.

**How to reproduce: add local group and add there local administrators.**

Tested with: computer in AD, computer without AD.
OS: Windows Server 2012 R2, Powershell: 5.0.10586.117

Tested with:
- domain Domai Admin account
- local account (created user)
- NT AUTHORITY\\SYSTEM
- direct local Administrator with password

Effects are the same

**Comment by kwirkykat** [comment]
@marcinbojko It looks like you are using the Group resource from PSDesiredStateConfiguration. The Group resource from PSDscResources is much more updated and may already have a fix for this issue. It looks like you are using WMF 5.0 though and PSDscResources only works with WMF 5.1 (but currently not the downloadable version 😢).

So, can you try using xGroup from xPSDesiredStateConfiguration instead? It should be basically the same resource as Group in PSDscResources, but you should be able to use it on WMF 4.0+

You will need xPSDesiredStateConfiguration installed on whatever machine you are running on and you will need to change this part of your code
```powershell
$invokeParams = @{
  Name          = 'xGroup'
  Method        = 'test'
  Property      = @{
    groupname = 'new-group'
    ensure = 'present'
    members = @('.\Administrators')
    credential = [PSCustomObject]@{'password' = 'password'; 'user' = '.\Administrator'} | new-pscredential
  }
  Verbose =$true
  ModuleName = "xPSDesiredStateConfiguration"
}
```

**Comment by Zuldan** [comment]
@kwirkykat we really would like to move to the latest PSDscResources on our 2012 R2 servers. The PS Team said they weren't going to be releasing 5.1 in Dec because part of the team would be on leave. So the plan was to release it early Jan. We are well past 'early' Jan :(. Do you have any info as to why it's been delayed again?

**Comment by kwirkykat** [comment]
@Zuldan Honestly, I have no idea. Sorry. I'm also anxiously awaiting the new 5.1 release...

**Comment by kwirkykat** [comment]
@Zuldan Ironically, they just released it: https://blogs.msdn.microsoft.com/powershell/2017/01/19/windows-management-framework-wmf-5-1-released/

**Comment by marcinbojko** [comment]
@kwirkykat 
Switched to xGroup (I switched almost all my mods to xPSDesiredStateConfiguration)
The error is the same:

```
$script:ErrorActionPreference = 'Stop'
$script:WarningPreference     = 'SilentlyContinue'

function new-pscredential
{
  [CmdletBinding()]
  param (
    [parameter(Mandatory=$true,
      ValueFromPipelineByPropertyName=$true)]
    [string]
    $user,

    [parameter(Mandatory=$true,
      ValueFromPipelineByPropertyName=$true)]
    [string]
    $password
  )

  $secpasswd   = ConvertTo-SecureString $password -AsPlainText -Force
  $credentials = New-Object System.Management.Automation.PSCredential ($user, $secpasswd)
  return $credentials
}

$response = @{
  indesiredstate = $false
  rebootrequired = $false
  errormessage   = ''
}

$invokeParams = @{
  Name          = 'xGroup'
  Method        = 'test'
  Property      = @{
    groupname = 'new-group'
    ensure = 'present'
    members = @('HOME\Domain Admins', 'Administrators')
    credential = [PSCustomObject]@{'password' = 'somepassword'; 'user' = 'someadmin'} | new-pscredential
  }
  Verbose=$true
  ModuleName = @{
    ModuleName      = "C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/dsc_resources/xPSDesiredStateConfiguration/xPSDesiredStateConfiguration.psd1"
    RequiredVersion = "5.0.0.0"
  }
}

try{
    $result = Invoke-DscResource @invokeParams
}catch{
  $response.errormessage   = $_.Exception.Message
  return ($response | ConvertTo-Json -Compress)
}

# keep the switch for when Test passes back changed properties
switch ($invokeParams.Method) {
  'Test' {
    $response.indesiredstate = $result.InDesiredState
    return ($response | ConvertTo-Json -Compress)
  }
  'Set' {
    $response.indesiredstate = $true
    $response.rebootrequired = $result.RebootRequired
    return ($response | ConvertTo-Json -Compress)
  }
}
```

Running in Verbose gives me:

> VERBOSE: [W2K12]:                            [[xGroup]DirectResourceAccess] Resolving Domain Admins in the domain HOME.
> Exception calling ".ctor" with "4" argument(s): "The server could not be contacted."
>     + CategoryInfo          : InvalidOperation: (:) [], CimException
>     + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
>     + PSComputerName        : localhost
>  
> VERBOSE: [W2K12]: LCM:  [ End    Test     ]  [[xGroup]DirectResourceAccess] False in 7.4140 seconds.
> The PowerShell DSC resource '[xGroup]DirectResourceAccess' with SourceInfo '' threw one or more non-terminating errors while running the Test-TargetResource functionalit
> y. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
>     + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
>     + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
>     + PSComputerName        : localhost
>  
> VERBOSE: Operation 'Invoke CimMethod' complete.
> VERBOSE: Time taken for configuration job to complete is 7.758 seconds
> {"rebootrequired":false,"indesiredstate":null,"errormessage":""}

**Comment by marcinbojko** [comment]
Switching to version 5.1.0.0 gives the same results:

>   ModuleName = @{
>     ModuleName      = "C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\5.1.0.0\xPSDesiredStateConfiguration.psd1"
>     RequiredVersion = "5.1.0.0"

> VERBOSE: [W2K12]: LCM:  [ End    Test     ]  [[xGroup]DirectResourceAccess] False in 6.2200 seconds.
> PowerShell DSC resource MSFT_xGroupResource  failed to execute Test-TargetResource functionality with error message: Exception calling ".ctor" with "4" argument(s): "The server could not be 
> contacted." 
>     + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
>     + FullyQualifiedErrorId : ProviderOperationExecutionFailure
>     + PSComputerName        : localhost

**Comment by kwirkykat** [comment]
@marcinbojko Hmmmm. Have you tried it with a group name that doesn't have a '-' in it? Like 'NewGroup' instead of 'New-Group'?

It looks like it's failing after that when it is trying to resolve the group members though. I'm looking into it.

**Comment by marcinbojko** [comment]
Sorry @kwirkykat - I don't think that was it ;(
Again - set goes perfectly, and second run (with test) fails.

> $invokeParams = @{
>   Name          = 'xGroup'
>   Method        = 'test'
>   Property      = @{
>     groupname = 'newgroup'
>     ensure = 'present'
>     members = @('HOME\Domain Admins', 'Administrators')

> PowerShell DSC resource MSFT_xGroupResource  failed to execute Test-TargetResource functionality with error message: Exception calling ".ctor" with "4" argument(s): "The server could not be 
> contacted." 
>     + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
>     + FullyQualifiedErrorId : ProviderOperationExecutionFailure
>     + PSComputerName        : localhost

**Comment by Zuldan** [comment]
@kwirkykat haha, I should have waited a little more. Really happy it's released now.

**Comment by kwirkykat** [comment]
@marcinbojko Yeah I was doubtful the group name change would fix it. Usually this error comes up when the username of one of the members or the domain of one of the members cannot be resolved. I see you are defining 'HOME\Domain Admins' and 'Administrators' as the members of the group. Are these usernames or the names of other groups?

**Comment by marcinbojko** [comment]
@kwirkykat 
We have 50/50 situation here:
Mentioned machine is a member of my test AD Domain called 'HOME'.
Now, we are creating new group in machine called hmmm... 'new-group', and we are trying to add both:
HOME\Domain Admins (built in domain account) na local Administrators *Built in Administrators).
Both names are resolvable - 'set' phase makes the proper changes: creates group 'new-group' with members: HOME\Domain Admins and .\Administrators.

**Comment by kwirkykat** [comment]
@marcinbojko I'm not sure that xGroup works to create a group of groups. I've only seen it used to create a group of users. But you said the first time through works right? So it sounds like it's fine. Maybe the second time it comes back, it's no longer running under the correct credentials? Even though I'm assuming you applied the same parameters both times. It could be that Set attempts to grant the two groups permissions to log on as a service, but because they are groups instead of users, something weird is getting messed up in the system which causes it to fail the second time. Still investigating...

@TravisEz13 Have you seen group work with a group of groups? Any idea why this config is failing on the second run?

**Comment by marcinbojko** [comment]
xGroup should work with creating or modifying groups. One of features in AD/Windows Server is a feature called nested groups - groups that can have other groups. Those test were conducted on  Windows 2012 R2 and Windows 2016.
In mentioned example, adding anything besides local groups - works. What's strange - 'set' works, but it fails on second run. 
From my digging, it looks like some kind of permission issue.

**Comment by kwirkykat** [comment]
@marcinbojko Have you tried this with the new release (6.0.0.0)? There were some bug fixes to xGroup that may fix your problem

**Comment by marcinbojko** [comment]
Hi @kwirkykat 
I am still waiting for puppetlabs/dsc to be released with all new bugfixes. I'll do a test run with 6.0.0.0 on the side.

**Comment by marcinbojko** [comment]
@kwirkykat - I would like to report that with latest release of xPSDesiredStateConfiguration (probably from 6.0.0.0 as you suggested) the bug is gone. :)
Should I close this issue?
