### ISSUE TITLE
xPackage - logging underlying exception message

### ISSUE THREAD

**Issue by mgr32** [PowerShell/xPSDesiredStateConfiguration#31]
When using xPackage and process fails to run, the error message does not state what the actual problem is, which makes is hard for troubleshooting. Consider following script that tries to run an empty .bat file:

    $filePath = 'c:\invalid.bat'

    Configuration Test {
    Import-DSCResource -ModuleName xPSDesiredStateConfiguration

        xPackage TestPackage {
            Name = 'Test'
            Path = $filePath
            ProductId = ''
        }
    }

    [void](New-Item -Path $filePath -ItemType File -Force -Value '')
    Test -OutputPath .\Test
    Start-DscConfiguration -Path .\Test -Wait -Verbose -Force

When run, we only get the following message (both on console and in Event Log):

*PowerShell DSC resource MSFT_xPackageResource failed to execute Set-TargetResource functionality with error message: The process c:\invalid.bat could not be started*

so we don't really know what happened. Similarly, when an Access Denied occurs (much more probable in real life scenarios), we'll get the same, not very helpful, message.

If we change how errors are thrown in MSFT_xPackageResource (see following [commit](https://github.com/mgr32/xPSDesiredStateConfiguration/commit/451e0d526f4c7f1905efde7f84967f4e1b34d905)) we can get much better message:

*PowerShell DSC resource MSFT_xPackageResource failed to execute Set-TargetResource functionality with error message: The process c:\invalid.bat could not be started: Exception calling "Start" with "0" argument(s): "The specified executable is not a valid application for this OS platform." / at Set-TargetResource, C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration\DscResources\MSFT_xPackageResource\MSFT_xPackageResource.psm1: line 841*

Do you think the error messages could be updated across the modules, so that the actual error message from the underlying exception is always logged? See also question titled [Error handling in MSFT_xWebsite and others](https://gallery.technet.microsoft.com/scriptcenter/DSC-Resource-Kit-All-c449312d/view/Discussions/2) for similar issue in xWebsite.

**Comment by KarolKaczmarek** [comment]
Thanks @mgr32, this is definitely a valid point and outputting additional information will provide better user/developer experience. Could you please send PR with the commit you linked to?
