### ISSUE TITLE
xGroup doesn't work properly on domain controller.

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/xPSDesiredStateConfiguration#32]
A local user is created under and added to admin group and then machine was promoted to DC. After that consistency checks fails as xGroup resource is not able to resolve local user (now domain controller admin). 
Prior to promoting to a DC, the members were all local users and they are resolved using the PrincipalContext for the local system and no credentials are needed.  After promotion, the members are changed to domain users and reported as such.  Since the xGroup resource expects domain credentials to resolve domain entries; it reports an error.

**Comment by kwirkykat** [comment]
This is probably related to #19

**Comment by TravisEz13** [comment]
FYI, there also are no local groups after a DC promo.  Should xGroup be allowed on a DC?

**Comment by johlju** [comment]
I agree that this should not be used on a domain controller, [xADGroup](https://github.com/PowerShell/xActiveDirectory#xadgroup) could be used to manage the AD groups once promoted. Is there a scenario where it's needed to set local groups prior to promoting a DC?
