### ISSUE TITLE
xPSDesiredSTateConfiguration not reading xDscWebService in Server 2016

### ISSUE THREAD

**Issue by iwifia** [PowerShell/xPSDesiredStateConfiguration#327]
following a build script to build a new DSC pull server in 2016.

Code is as follows.

` 
       Install-Module -Name xPSDesiredStateConfiguration
      
      Configuration CreatePullServer {
      param (
       [string[]]$ComputerName = 'localhost'
      )

      Import-DSCResource -ModuleName xPSDesiredStateConfiguration
      Import-DSCResource –ModuleName PSDesiredStateConfiguration

      Node $ComputerName {
      WindowsFeature DSCServiceFeature {
       Ensure = "Present"
       Name  = "DSC-Service"
     }

    xDscWebService 'PSDSCPullServer' {
      Ensure         = "Present"
      EndpointName      = "PSDSCPullServer"
      Port          = 8080
      PhysicalPath      = "$env:SystemDrive\inetpub\wwwroot\PSDSCPullServer"
      CertificateThumbPrint  = "AllowUnencryptedTraffic"
      ModulePath       = "$env:PROGRAMFILES\WindowsPowerShell\DscService\Modules"
      ConfigurationPath    = "$env:PROGRAMFILES\WindowsPowerShell\DscService\Configuration"
      State          = "Started"
      DependsOn        = "[WindowsFeature]DSCServiceFeature"
      }
     }
    }`

Error is as follows

`    At line:21 char:5
    +     xDscWebService 'PSDSCPullServer' {
    +     ~~~~~~~~~~~~~~
     Resource 'xDSCWebService' requires that a value of type 'Boolean' be provided for property   UseSecurityBestPractices'.
         + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
         + FullyQualifiedErrorId : MissingValueForMandatoryProperty`

**Comment by megamorf** [comment]
So? The error message `Resource 'xDSCWebService' requires that a value of type 'Boolean' be provided for property 'UseSecurityBestPractices'.` tells you that you're missing the `UseSecurityBestPractices` for your `xDscWebService 'PSDSCPullServer'` stanza.

**Comment by iwifia** [comment]
Yeah nevermind... reading it when you re-wrote I got it. Worked in 2012R2 because that wasn't required. 2016 it is.
