### ISSUE TITLE
xRegistry Dword fails when value is ffffffff

### ISSUE THREAD

**Issue by jmpetty21** [PowerShell/xPSDesiredStateConfiguration#332]
I have a need to make a register key (”HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters”) a DWord with the value of ffffffff. 

I receive the following error.
Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."

Here is my configuration
xRegistry DisabledComponents{
        Ensure      = "Present"
        Key         = ”HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters”
        ValueName   = ”DisabledComponents”
        ValueData   = 'ffffffff'
        ValueType   = "DWord" 
    }

**Comment by megamorf** [comment]
You're missing the hex parameter

**Comment by kwirkykat** [comment]
@jmpetty21 Does this work if you add `Hex = $true` to your parameters as @megamorf suggested?

**Comment by jmpetty21** [comment]
Sorry for the delay, yes using the HEX value resolved the issue. Thanks for the help!!
