### ISSUE TITLE
xPSDesiredStateConfiguration/Examples/Sample_xDscWebServiceRegistrationWithSecurityBestPractices.ps1 $thumbprint

### ISSUE THREAD

**Issue by timhaintz** [PowerShell/xPSDesiredStateConfiguration#340]
In the example (xPSDesiredStateConfiguration/Examples/Sample_xDscWebServiceRegistrationWithSecurityBestPractices.ps1), $thumprint is used as an argument. 

[ValidateNotNullOrEmpty()]
        [string] $certificateThumbPrint
&
CertificateThumbPrint   = $certificateThumbPrint

However $certificateThumbPrint is used as arguments inside the DSC code block. Need to update the argument $thumbprint to $certificateThumbPrint.

Sorry, don't know how to do a pull request yet and fix it myself.

Thanks, Tim.

**Comment by kwirkykat** [comment]
Fixed in PR #356

**Comment by timhaintz** [comment]
Thanks.
