### ISSUE TITLE
DSC Failing on particular VM but not others, odd error

### ISSUE THREAD

**Issue by michaelseto** [PowerShell/xPSDesiredStateConfiguration#342]
I am using the Set-AzureRmVmDscExtension cmdlet to excute a DSC script on a target VM. The DSC script is kept in a zip file in BLOB storage, that cmdlet takes the -ArchiveBlobName and -ArchiveStorageAccountName switches to know which storage account and which zip file.

The strange thing happening is, this script had success on 3 out of 4 VM's, but keeps failing on one same VM.

I have searched all around for what this error means, but cannot find it. I am making an assumption that it is related to this DSC resource?

Error ::

Status              : Failed
StatusCode          : OK
RequestId           : 616acd51-ad88-4ac6-b8f1-c394ead7e4d4
Output              : 
Error               : {
                        "Details": [],
                        "InnerError": null,
                        "Code": "VMExtensionProvisioningError",
                        "Message": "VM has reported a failure when processing extension 'Microsoft.Powershell.DSC'. Error message: \"The DSC Extension received an incorrect input: A parameter cannot be found that matches parameter name 
                      'ResourceModuleTuplesToImport'.\n\nAnother common error is to specify parameters of type PSCredential without an explicit type. Please be sure to use a typed parameter in DSC Configuration, for example:\n\n    configuration Example 
                      {\n        param([PSCredential] $UserAccount)\n        ...\n    }.\nPlease correct the input and retry executing the extension.\".",
                        "Target": null
                      }
StartTime           : 4/22/2017 7:45:46 PM -04:00
EndTime             : 4/22/2017 7:47:06 PM -04:00
TrackingOperationId : 2ca301c6-57c5-4fea-b491-4eb650fc859c

Again, this has already worked on three other VM's. I actually used a loop to run it on all four and 3 had success and one failed (and keeps failing). Yes, each time I try again I make sure to uninstall the DSC extension from the VM.

**Comment by michaelseto** [comment]
Using -Version 2.21 of DSC as well

**Comment by kwirkykat** [comment]
@michaelseto This has nothing to do with xPSDesiredStateConfiguration, so I can't help you with this here. I don't think 'ResourceModuleTuplesToImport' is a parameter to the DSC extension though. You will need ask Azure support about this issue if you need help.
