### ISSUE TITLE
xRegistry Binary Value Confusion

### ISSUE THREAD

**Issue by sam-cogan** [PowerShell/xPSDesiredStateConfiguration#362]
I'm trying to use xRegistry to replicate the change made in the reg file below, but I am hitting an issue where whatever format I use for the value data I get an "not in the correct hex format to parse as Byte Array" , this includes adding 0x to the front of each value. Can someone confirm the correct format to use for the DSC resource for this:

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lanmanserver\DefaultSecurity]
"SrvsvcShareAdminConnect"=hex:01,00,04,80,64,00,00,00,70,00,00,00,00,00,00,00,\
  14,00,00,00,02,00,50,00,03,00,00,00,00,00,18,00,03,00,0f,00,01,02,00,00,00,\
  00,00,05,20,00,00,00,20,02,00,00,00,00,18,00,03,00,0f,00,01,02,00,00,00,00,\
  00,05,20,00,00,00,25,02,00,00,00,00,18,00,03,00,0f,00,01,02,00,00,00,00,00,\
  05,20,00,00,00,27,02,00,00,01,01,00,00,00,00,00,05,12,00,00,00,01,01,00,00,\
  00,00,00,05,12,00,00,00

**Comment by mkht** [comment]
Try this.
```PowerShell
xRegistry SrvsvcShareAdminConnect
{
    Key = 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lanmanserver\DefaultSecurity'
    ValueName = 'SrvsvcShareAdminConnect'
    ValueType = 'Binary'
    ValueData = '010004806400000070000000000000001400000002005000030000000000180003000f00010200000000000520000000200200000000180003000f00010200000000000520000000250200000000180003000f0001020000000000052000000027020000010100000000000512000000010100000000000512000000'
    Force = $true
}
```

**Comment by johlju** [comment]
@sam-cogan did the previous comment answer your question?

**Comment by sam-cogan** [comment]
Sorry, should have come back to this. Yes this resolved it and I was able to get it working.
