### ISSUE TITLE
On 64 bit system run pullserver in 64 bit procsess instead of 32 bit.

### ISSUE THREAD

**Issue by BerheAbrha** [PowerShell/xPSDesiredStateConfiguration#364]
ESENT db has limitation or a bug when the size of the database exceeds 128 GB in a 32 bit process. The recommendation from the ESENT team is to run the process in 64 bit.  This can be configured though the IIS application pool -> advance setting (Enable 32 bit application = False).  So this bug is to update the pull server setup to do this by default.

**Comment by Indhukrishna** [comment]
Fixed with #372
