### ISSUE TITLE
Lots of ESENT Errors and stale DB.

### ISSUE THREAD

**Issue by Outek** [PowerShell/xPSDesiredStateConfiguration#368]
I have troubles with the ESENT Database.
All Agents can register for some time, but after 3-5min lots of ESENT errors appears in the Eventlog and no client can't register any more nor get Reports from the pullserver.

The troubles are very similiar like this issue: https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/296

Version of Microsoft.Powershell.DesiredStateConfiguration.Service.dll
10.0.14393.479

PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                                                                                 
----                           -----                                                                                                                                                                                 
PSVersion                      5.1.14393.1532                                                                                                                                                                        
PSEdition                      Desktop                                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                               
BuildVersion                   10.0.14393.1532                                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                                   
SerializationVersion           1.1.0.1 

ImplementedAs   Name                      ModuleName                     Version    Properties                                        
-------------   ----                      ----------                     -------    ----------                                        
PowerShell      xDSCWebService            xPSDesiredStateConfiguration   7.0.0.0

Eventlogs Message:
w3wp (6392) PSDSCPullSever: The version store for this instance (0) has reached its maximum size of 15Mb. It is likely that a long-running transaction is preventing cleanup of the version store and causing it to build up in size. Updates will be rejected until the long-running transaction has been completely committed or rolled back. 
Possible long-running transaction: 
	SessionId: 0x156E6B00 
	Session-context: 0x00000000 
	Session-context ThreadId: 0x00000CBC 
	Cleanup: 1 
	Session-trace: 
57573@11:50:31

and sometimes:
w3wp (4172) A significant portion of the database buffer cache has been written out to the system paging file. This may result in severe performance degradation. 
See help link for complete details of possible causes. 
Previous cache residency state: 100% (4143 out of 4143 buffers) (184 seconds ago) 
Current cache residency state:  79% (39107 out of 48972 buffers) 
Current cache size vs. target:  100% (191.773 / 191.773 MBs) 
Physical Memory / RAM size:     4094.918 MBs

Is it possible, to increase the maximum size of the version store?
Thank you for any suggestion.

**Comment by Outek** [comment]
w3wp (3044) PSDSCPullSever: An attempt to open the file "D:\DscService\edb.log" for read only access failed with system error 32 (0x00000020): "The process cannot access the file because it is being used by another process. ".  The open file operation will fail with error -1032 (0xfffffbf8).

w3wp (3044) PSDSCPullSever: Error -1032 (0xfffffbf8) occurred while opening logfile D:\DscService\edb.log.

**Comment by johlju** [comment]
@Outek If this is still a problem I suggest you report this as a problem to Microsoft Support to see if you can get help trough there.

>Following this release of Windows Pull Server, there are no additional plans to release new features to the pull service capability in Windows Server. Support for Windows Pull Server in production environments will continue following the Windows Server support lifecycle.
>[Windows Pull Server Planning Update – April 2018](https://blogs.msdn.microsoft.com/powershell/2018/04/19/windows-pull-server-planning-update-april-2018/)

Closing this as external since we can't resolve this in this resource module.
