### ISSUE TITLE
Obtain latest production version of PSDesiredStateConfiguration

### ISSUE THREAD

**Issue by arcotek-ltd** [PowerShell/xPSDesiredStateConfiguration#371]
Sorry to ask this here but it seems like the best place to get an answer.

Even on Windows 10 Enterprise with the latest updates installed, PSDesiredStateConfiguration is at version 1.1, whereas xPSDesiredStateConfiguration is showing version 7.0.0.0 in PowerShell Gallery.

Is there an update to the production version and if so how does one get it:
1. `Update-Module PSDesiredStateConfiguration` 
2. Some MS update.

If there isn't currently a production update available, when there is, how does Microsoft expect to package such an update. Via PSGallery or an update?

I'm specifically interested in the addition of the timeout parameters in MSFT_ServiceResource as in version 1.1, a service has 2 seconds to start.

Thanks and apologies again.

**Comment by johlju** [comment]
Sorry that you haven't gotten an answer for so long.

PSDesiredStateConfiguration is the built-in resources (shipped with Windows). What I understand there is no more development on the in-box resources. The resource module PSDscResources module in PowerShell Gallery have new versions of these, except for File, Log and Package. When PSDscResources are installed the resources in PSDscResources will override those in PSDesiredStateConfiguration. 

*Note: xPSDesiredStateConfiguration have a xPackage resource.*

Please submit any issue for enhancements to PSDscResources and xPSDesiredStateConfiguration.

**Comment by johlju** [comment]
I'm closing this as answered. Please reopen or comment if this was closed in error.
