### ISSUE TITLE
What is the purpose of the Publish functions?

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/xPSDesiredStateConfiguration#373]
So I came across `Publish-ModuletoPull` server and `Publish-MofToPullServer`. At first I thought these were commands to make it easier to push stuff from an authoring box. But instead it looks like you have to run these commands on the pull server, otherwise, the web.config is irrelevant. I suppose I could stage MOFs from the authoring box to an intermediate folder on the pull server and then publish but that seems like a lot of extra work. Or am I missing something?

**Comment by anwather** [comment]
No it has to be run from the pull server.

**Comment by johlju** [comment]
Closing this as answered as per previous comment. Please reopen or comment if this was closed in error.
