### ISSUE TITLE
Use SQL Server Database for DSC Pull Server configuration instead of ESENT DB

### ISSUE THREAD

**Issue by llowevad** [PowerShell/xPSDesiredStateConfiguration#374]
Are there plans to incorporate an option to point the backend database for a DSC Pull Server to a remote SQL Server?

If so, when do you think this will happen?

My customer wants to get a better availability setup along with simplified custom reporting. SQL Server databases will help with both scenarios not to mention scalability and performance in larger environments.

**Comment by mgreenegit** [comment]
Please add to votes here:
https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088516-change-from-edb-file-to-sql-server-database-for-de

And then this issue can be closed out, thanks.

**Comment by johlju** [comment]
This has now been added as per [Windows Pull Server Planning Update – April 2018](https://blogs.msdn.microsoft.com/powershell/2018/04/19/windows-pull-server-planning-update-april-2018/)
