### ISSUE TITLE
KB4035631 may have broken connecting Pull Server to SQL 

### ISSUE THREAD

**Issue by mthames** [PowerShell/xPSDesiredStateConfiguration#377]
KB4035631 contained an update to Jet 4.0 which I believe may be causing issues with connecting DSC Pull Server to SQL.

Server OS: Server 2016
SQL Version: SQL Server 2016 Enterprise with SP1 (Loaded on same server as Pull Server)

Error (Event Log):  Unable to retrieve Agent Id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx from the database.  The underlying error is "The 'Microsoft.Jet.OLEDB.4.0' provider is not registered on the local machine.

Error:  (When trying to register nodes with the Pull Server)  - returned unexpected response code InternalServerError. .

I have setup Pull Servers in the past using the same setup as above and not had any issues.  Only difference I can find is the update KB4035631 which updated Jet 4.0 for the first time in years.

**Comment by anwather** [comment]
Two things I found that worked - set the xDSCWebService property Enable32BitAppOnWin64 = $true.

Or - create a 64 bit ODBC connection and then install the x64 version of https://www.microsoft.com/en-us/download/details.aspx?id=13255 (Access Database Engine 2010 Redistributible)

**Comment by anwather** [comment]
Also have to change the provider to Microsoft.ACE.OLEDB.12.0 in web.config

**Comment by johlju** [comment]
I'm closing this as there are now SQL Server support in the latest Windows Server Pull Server, see [Windows Pull Server Planning Update – April 2018](https://blogs.msdn.microsoft.com/powershell/2018/04/19/windows-pull-server-planning-update-april-2018/).
