### ISSUE TITLE
Cannot process argument because the value of argument "fullFilePath" is not valid

### ISSUE THREAD

**Issue by jmpetty21** [PowerShell/xPSDesiredStateConfiguration#382]
PowerShell all of a sudden started throwing this error when I am trying to create MOF files. 
```
At line:1 char:15
+ Configuration xServiceSetStartExample
+               ~~~~~~~~~~~~~~~~~~~~~~~
System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "fullFilePath" is not valid. Change the value of the "fullFilePath" argument and run the operation again.
   at Microsoft.PowerShell.DesiredStateConfiguration.CimDSCParser.GetFileContent(String fullFilePath)
   at Microsoft.PowerShell.DesiredStateConfiguration.CimDSCParser.ParseSchemaMof(String filePath)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.ImportClasses(String path, Tuple`2 moduleInfo, Collection`1 errors, Boolean importInBoxResourcesImplicitly)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.Initialize(Collection`1 errors, List`1 modulePathList)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Dictionary`2 functionsToDefine, Collection`1 errors, List`1 modulePathList, Boolean cacheResourcesFromMultipleModuleVersions)
   at System.Management.Automation.Language.Parser.ConfigurationStatementRule(IEnumerable`1 customAttributes, Token configurationToken)
At line:2 char:1
+ {
+ ~
Unexpected token '{' in expression or statement.
At line:11 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParserError
```

Here is the sample configuration I am trying to use 
```
Configuration TimeZone
{
    Import-DscResource -ModuleName 'xTimeZone'

        xTimeZone Central{
            IsSingleInstance = 'yes'
            TimeZone         = 'Eastern Standard Time'
        }
}
```

**Comment by johlju** [comment]
@dazinator Are you getting the same error? Could you provide your configuration and verbose log output when you get this? Also on which OS and WMF version are you getting the error?

**Comment by joerianto83** [comment]
hi there, just want to reopen, i have the same error message, but from another perspective.
just trying to run the dscconfiguration file that generates the MOF file, from a Powershell Task in Azure Devops.  Running it from any local powershell prompt or command prompt it's all working fine.

**Issue:** generate LCM MOF or DSC configuration MOF within the Powershell Task in Azure DevOps
![powershelltask](https://user-images.githubusercontent.com/43513686/58118633-9221a200-7c01-11e9-88bd-a9521de15553.PNG)
**Explaination:** so normally you just call your dsc configuration i.e. myconfig.ps1 and within the file i already mentioned the dsc configuration NAME. after that it will generate the MOF file. if i do the same, calling this myconfiguration.ps1 file within the Powershell Task(inline task same error) , it wont generate the file.

**Sample:** See below a sample code that i have saved in .ps1 file Configuration myconfig { Import-DscResource -ModuleName PSDesiredStateConfiguration
Service OIService { Ensure = "Present" Name = "HealthService" State = "Running"
}
} myconfig -OutputPath c:\myconfig

by calling the this myconfig.ps1 powershell file with the powershell task in azuredevops it results in below error.

**Error:**
![image](https://user-images.githubusercontent.com/43513686/58118539-5d154f80-7c01-11e9-9eb2-2036782b3c0f.png)
