### ISSUE TITLE
xRemoteFile is very slow

### ISSUE THREAD

**Issue by draggeta** [PowerShell/xPSDesiredStateConfiguration#383]
I noticed that downloading files with xRemoteFile is very slow. From what I've read in the link below and the tests I've performed, I can confirm that it is due to the way the progress bar is rendered. This is really bad. Is it possible to disable the progress bar in the xRemoteFile cmdlet?

Something as silly as this should work:
```powershell
# Invoke web request
try
{
    Write-Verbose -Message $($LocalizedData.DownloadingURI `
        -f ${DestinationPath},${URI})
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest @PSBoundParameters -Headers $headersHashtable -outFile $DestinationPath
}
catch [System.OutOfMemoryException]
{
    ...
}
catch [System.Exception]
{
    ...
}
finally 
{
    $ProgressPreference = 'Continue'
}
```

More info can be found here:
https://github.com/PowerShell/PowerShell/issues/2138

**Comment by johlju** [comment]
It is not possible today. This is being worked on in PR #390.
