### ISSUE TITLE
Cannot process Cmdlet Definition XML

### ISSUE THREAD

**Issue by robwaldron** [PowerShell/xPSDesiredStateConfiguration#39]
I'm trying to dynamically build configuration scripts in C# using PowerShell 5 Preview, but unfortunately i'm receiving the following error:

Exception	{"Cannot process Cmdlet Definition XML for the following file: C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\PSDesiredStateConfiguration\\Remove-DscConfigurationDocument.cdxml. There is an error in XML document (33, 31). Object reference not set to an instance of an object."}	System.Exception {System.Xml.XmlException}

You can test this with the following ConsoleApp code:

```
namespace ConsoleApplication1
{
    using System;
    using System.Management.Automation;
    using System.Threading;

    class Program
    {
        static void Main(string[] args)
        {
            using (PowerShell PowerShellInstance = PowerShell.Create())
            {
                PowerShellInstance.AddScript(@"Configuration Web
                {
                    Import-DscResource -ModuleName ""PSDesiredStateConfiguration""

                    Node Website
                    {
                        WindowsFeature 'IIS'
                        {
                            Ensure = 'Present'
                            Name = 'web-server'
                            IncludeAllSubFeature = $true
                        }
                    }
                }

                Web -OutputPath C:\Temp");

                PSDataCollection<PSObject> outputCollection = new PSDataCollection<PSObject>();
                outputCollection.DataAdded += outputCollection_DataAdded;
                PowerShellInstance.Streams.Error.DataAdded += Error_DataAdded;

                IAsyncResult result = PowerShellInstance.BeginInvoke<PSObject, PSObject>(null, outputCollection);

                while (result.IsCompleted == false)
                {
                    Console.WriteLine("Waiting for pipeline to finish...");
                    Thread.Sleep(1000);
                }

                Console.WriteLine("Execution has stopped. The pipeline state: " + PowerShellInstance.InvocationStateInfo.State);

                foreach (PSObject outputItem in outputCollection)
                {
                    //TODO: handle/process the output items if required
                    Console.WriteLine(outputItem.BaseObject.ToString());
                }
            }
        }

        static void outputCollection_DataAdded(object sender, DataAddedEventArgs e)
        {
            Console.WriteLine("Object added to output.");
        }

        static void Error_DataAdded(object sender, DataAddedEventArgs e)
        {
            Console.WriteLine("An error was written to the Error stream!");
        }
    }
}
```

**Comment by PlagueHO** [comment]
Wow! This one is old!

@robwaldron - Have you tried this in the PS 5.0 RTM release from earlier this year? Does it still occur with that version?

I built the above console app in VS 2015 and ran it on a box with PS 5.0 RTM - looks like the problem has been resolved:
![2016-06-08_20-02-00](https://cloud.githubusercontent.com/assets/7589164/15887028/0e2895e2-2db4-11e6-9bb6-c711be243cc8.png)

If it is resolved can we close this one?

**Comment by kwirkykat** [comment]
@robwaldron Any updates?
It looks like you are using the in-box PSDesiredStateConfiguraiton rather than open-source xPSDesiredStateConfiguration.

I will close this tomorrow if there's no update.

**Comment by TravisEz13** [comment]
In addition to what @kwirkykat, [PowerShell User Voice](https://windowsserver.uservoice.com/forums/301869-powershell) is a better place for reporting issues with inbox PowerShell DSC.

**Comment by robwaldron** [comment]
Hey guys - Thanks for getting back to me. Ended up coming up with a work around, but yes this now works which is excellent! I'll now continuing trekking down this path.
