### ISSUE TITLE
xRemoteFile failing on https

### ISSUE THREAD

**Issue by fred070** [PowerShell/xPSDesiredStateConfiguration#393]
Hi, 

I'm trying to download the url: https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Windows-x86_64.exe but it's giving me an error.

> PowerShell DSC resource MSFT_xRemoteFile  failed to execute Set-TargetResource functionality with error message: Invoking web request failed with error. The request was aborted: Could not create SSL/TLS secure channel.  The SendConfigurationApply function did not succeed. LCM failed to start desired state configuration manually.

I saw a post in stackoverflow that `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` should do the trick. I haven't tried that because I don't know where to put it. :(

Here's the sample code in my DSC file: 
```
xRemoteFile DockerComposeInstall
{
    DestinationPath = "$env:ProgramFiles\docker\docker-compose.exe"
    Uri = $dockercomposeUrl
}
```

**Comment by PlagueHO** [comment]
Hi @fred070, you'd need to use the xScript resource to do this. I just had to enable TLS1.2 in another module I maintain and so I used the code I used in that to enable TLS1.2 (as it didn't disable old security protocols).

For example:
```powershell
xScript ScriptExample
{
    SetScript = {
                 [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol.toString() + ', ' + [Net.SecurityProtocolType]::Tls12
    }
    TestScript = {
       return ([Net.ServicePointManager]::SecurityProtocol -match 'Tls12')
    }
    GetScript = {
        return @{
            Result = ([Net.ServicePointManager]::SecurityProtocol -match 'Tls12')
        }
    }
}
```

@kwirkykat - I think we'll run into this problem more and more as sites move over to TLS1.2. So it might be a good idea to implement this in xRemoteFile itself (perhaps with an option to disable it). What are your thoughts?

Hope this helps!

**Comment by fred070** [comment]
Hi @PlagueHO , wonderful! This works. Thank you.

**Comment by jamesAMURR** [comment]
I'm having this issue too. Is there a significance to using xScript or can I just use Script? I would like to see this solved longer term. TLS 1.2 is mandatory at work.
