### ISSUE TITLE
How did I get reporting to SQL Working (AKA SQL Hack)

### ISSUE THREAD

**Issue by maroliict** [PowerShell/xPSDesiredStateConfiguration#396]
It took some time, but I figured out how to get this working.

We have the following machines:
DSC Pull Server
SQL Server hosting Database AND being one client for the pull server.

What I did…
First of all: I took the blog on https://blogs.technet.microsoft.com/fieldcoding/2017/05/11/using-sql-server-2016-for-a-dsc-pull-server/
Steps taken:

1.  On the SQL server I ran a script to create the database. It is an enhanced version of https://github.com/AutomatedLab/AutomatedLab/blob/master/LabSources/PostInstallationActivities/SetupDscPullServer/CreateDscSqlDatabase.ps1. 

2.  I updated the web.config on the Pull server to have 
<add key="dbprovider" value="System.Data.OleDb">
<add key="dbconnectionstr" value="Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\Program Files\WindowsPowerShell\DscService\Devices.mdb;">
instead of 
<add key="dbprovider" value="ESENT" />
<add key="dbconnectionstr" value="C:\Program Files\WindowsPowerShell\DscService\Devices.edb" />
3.  I added an ODBC DSN on the Pull server with the following command:
Add-OdbcDsn -Name DSC -DriverName 'SQL Server' -Platform '32-bit' -DsnType System -SetPropertyValue @('Description=DSC Pull Server', "Server=<Name of your SQL Server>", 'Trusted_Connection=yes', 'Database=DSC') –PassThru
4.  After this I added the Devices.mdb (mentioned in the blog above) to the D drive and gave permissions to that.

Looking at it, it should work…
But it doesn’t. 

First of all I figured out that the DSN is created, but is of the wrong type. This one gave TLS/SSL messages when you try to connect to the database. First of all I thought we messed up with the security providers, so took them from a clean machine and imported them on the Pull Server. Still the same error.
Then I looked at the versions of the ODBC providers and they were all of version 10.5.. which points me in the direction of SQL2008R2…. That is rather old. Are there new versions? 
I installed the connectivity tools of SQL2016 on the pull server. I only got the SQL Native Client 11.0 back. Wait… 11.0 Isn’t that… yes.. SQL2012. Rebooted the stuff.. Checked the client, still an error message about internal server error. Strange…
Or not? 
I then looked at the web.config again.. Doesn’t that say something about Microsoft.jet.OleDB.4.0?? That is something from Office 2003 and 2010.. But.. old is it.. Ok.. Let’s see… what options we have…Install different ODBC drivers?
Ok.. I downloaded the Access Database Engine x64 drivers and tried to install them on the Pull Server… Error message about missing VBCRuntime? Ok.. and continue. Huh wait.. office screen… next next finish… 
Reloaded the pull and sql server..
Still no joy

I then looked at that Web.config again.. hmmm. What do we have… still the old provider so I updated 
<add key="dbconnectionstr" value="Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\Program Files\WindowsPowerShell\DscService\Devices.mdb;">
To 
            <add key="dbconnectionstr" value="Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\DSC_MDB\Devices.mdb;"/>
Yes.. I also changed the directory where the Devices.mdb is stored. I hate the c-drive for storing data...
Restarted the website on the pull server and pushed the configuration again:
 
Huh? It is working.. but is it writing in the database?

 
Yes it is!! And it is even importing the existing old calls. That is great.

Lets look if we can find any data?
Yes there are tables filled with data in JSON format. This seems to work.

So… After some days of searching, we are able to write to the database. 

Some things to investigate:
- Why is one view not filled? Wrong things in the functions? wrong query? who knows?
- Find out which checks were successful and which one failed

**Comment by anwather** [comment]
The access database engine driver has been listed previously as the fix for this issue. When they changed the website pool to 64bit it broke this.

**Comment by anwather** [comment]
AFAIK the table which is empty has always been like that - I've never seen any data in it.

**Comment by anwather** [comment]
Issue #377

**Comment by maroliict** [comment]
you are right about this. It was written there indeed, I only made the story to be a complete sum up of things done to get it working.
Any idea why one of the functions in SQL seem to be broken. Breaking it down ends up with a sub-subquery delivering too many items back.

**Comment by anwather** [comment]
I think there is a 4000 character limit somewhere - it breaks the JSON conversion inside the view. Not sure if it was a limitation of the mdb database.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maroliict** [comment]
@kwirkykat We checked release 8.1.0.0 and saw the changes regarding the SQL parameters. What we haven't found is:

- Prerequirements for creating database or automate it via this module
- From what I read, there is no need for a DSN anymore and no need for an Access Database anymore. Is this $true?
- Is this now a supported situation?
- Is PowerBI still the way to get a clickable dashboard?

thanks in advance

**Comment by kwirkykat** [comment]
@amal-khalaf or @mgreenegit May be able to answer your questions better than I can

**Comment by johlju** [comment]
I'm closing this as there are now SQL Server support in the latest Windows Server Pull Server, see [Windows Pull Server Planning Update – April 2018](https://blogs.msdn.microsoft.com/powershell/2018/04/19/windows-pull-server-planning-update-april-2018/).

**Comment by maroliict** [comment]
I do not agree this completely. The source for the database itself is not mentioned anywhere.

**Comment by johlju** [comment]
@maroliict Sorry, I'm not following you. What do you mean by the 'The source for the database'?
