### ISSUE TITLE
8.1.0.0 xDscWebService Using SqlProvider and SqlConnectionString not working

### ISSUE THREAD

**Issue by HansOMartinsen** [PowerShell/xPSDesiredStateConfiguration#401]
The example (https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/Examples/Sample_xDscWebServiceRegistration_UseSQLProvider.ps1) does not work. I have installed a SQL Express locally and made sure SA is enabled (with mixed mode authentication enabled).

The error in the Pull server event log is:
Unable to retrieve Dsc Agent Information with AgentID = 3f755ca3-3185-11e8-90ed-005056a071a5. The underlying error is : Unable to retrieve Agent Id 3f755ca3-3185-11e8-90ed-005056a071a5 from the database. The underlying error is "Must declare the scalar variable "@agentId".".

The only investigation I see on this is the article https://blogs.msdn.microsoft.com/wushuai/2016/11/27/try-to-use-sql-server-as-dsc-pull-server-backend/
But that was before 8.1.0.0 released with these two parameters. What am I missing?

**Comment by rpinxten** [comment]
I have been struggling to get this to work also. What OS are you using? I understand you need at least WS2019 TP1 build 17623. This build contains a new Microsoft.Powershell.DesiredStateConfiguration.Service.dll. I am able to setup the pull server using the SQLConnectionString parameter in xDSCWebService, but no DSC database is created on my SQL box.

**Comment by johlju** [comment]
Please see the requirements and documentation in [Desired State Configuration Pull Service](https://docs.microsoft.com/en-us/powershell/dsc/pullserver).
