### ISSUE TITLE
"The server could not be contacted" MSFT_xGroupResource when using Test and xGroup

### ISSUE THREAD

**Issue by pjolsen** [PowerShell/xPSDesiredStateConfiguration#414]
I am attempting to invoke the following DSC code to test the members of the local administrators group on a member server (HOST1):
```
$invokeParams = @{
  Name          = 'xGroup'
  Method        = 'test'
  Property      = @{
    groupname = 'administrators'
    ensure = 'present'
    members = @( 'Administrator')
  }
  ModuleName = @{
    ModuleName      = "C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/dsc_resources/xPSDesiredStateConfiguration/xPSDesiredStateConfiguration.psd1"
    RequiredVersion = "8.0.0.0"
  }
}
Invoke-DscResource @invokeParams -Verbose -Debug 
```

The function fails with the below if there is any group or user as an existing member of the local administrators group that is not a local account (i.e. from the mydomain.com domain). HOST1 is a member of mydomain.com.

> VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourcetest,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
> VERBOSE: An LCM method call arrived from computer HOST1 with user sid S-1-5-21-2002561564-984300201-2854953705-500.
> VERBOSE: [HOST1]: LCM:  [ Start  Test     ]  [[xGroup]DirectResourceAccess]
> VERBOSE: [HOST1]:                            [[xGroup]DirectResourceAccess] Invoking the function Test-TargetResourceOnFullSKU for the group administrators.
> VERBOSE: [HOST1]:                            [[xGroup]DirectResourceAccess] A group with the name administrators exists.
> VERBOSE: [HOST1]:                            [[xGroup]DirectResourceAccess] Resolving Administrator as a local account.
> VERBOSE: [HOST1]: LCM:  [ End    Test     ]  [[xGroup]DirectResourceAccess] False in 4.2860 seconds.
> PowerShell DSC resource MSFT_xGroupResource  failed to execute Test-TargetResource functionality with error message:
> Exception calling ".ctor" with "2" argument(s): "The server could not be contacted."
>     + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
>     + FullyQualifiedErrorId : ProviderOperationExecutionFailure
>     + PSComputerName        : localhost
> 
> VERBOSE: Operation 'Invoke CimMethod' complete.
> VERBOSE: Time taken for configuration job to complete is 4.395 seconds

If we remove all the domain members from the administrators group, the test will complete successfully, as below: 

> VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourcetest,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
> VERBOSE: An LCM method call arrived from computer HOST1 with user sid S-1-5-21-2002561564-984300201-2854953705-500.
> VERBOSE: [HOST1]: LCM:  [ Start  Test     ]  [[xGroup]DirectResourceAccess]
> VERBOSE: [HOST1]:                            [[xGroup]DirectResourceAccess] Invoking the function Test-TargetResourceOnFullSKU for the group administrators.
> VERBOSE: [HOST1]:                            [[xGroup]DirectResourceAccess] A group with the name administrators exists.
> VERBOSE: [HOST1]:                            [[xGroup]DirectResourceAccess] Resolving Administrator as a local account.
> VERBOSE: [HOST1]:                            [[xGroup]DirectResourceAccess] Resolving Administrator as a local account.
> VERBOSE: [HOST1]: LCM:  [ End    Test     ]  [[xGroup]DirectResourceAccess] True in 5.7560 seconds.
> VERBOSE: [HOST1]: LCM:  [ End    Set      ]    in  9.5180 seconds.
> VERBOSE: Operation 'Invoke CimMethod' complete.
> 
> InDesiredState
> --------------
> True
> VERBOSE: Time taken for configuration job to complete is 9.679 seconds

I can run the same code in another domain (totally separate forest) and it works fine so I am suspecting that potentially there's something specific to the domain / environment causing the issue but I am struggling to determine what. Not sure if its relevant, but mydomain.com becomes "mydomaincom\domain administrators" (without the period in it) when I resolve the users. Needless to say that I am able to add domain objects via the GUI without issue.

**Comment by johlju** [comment]
@pjolsen would you mind testing the Group resource in https://github.com/PowerShell/PSDscResources if that solves you problem? There are [reported issues](https://github.com/PowerShell/PSDscResources/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Group+) with that resource as well, but maybe this particular issue is solved there.

**Comment by pjolsen** [comment]
The Test method appears to work OK on the PSDscResources module but add / remove do not work with a similar error:
PowerShell DSC resource MSFT_GroupResource  failed to execute Set-TargetResource functionality with error message: Exception calling "Remove" with "1" argument(s): "The network path was not found.
"
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

PowerShell DSC resource MSFT_GroupResource  failed to execute Set-TargetResource functionality with error message: Exception calling "Add" with "1" argument(s): "The network path was not found.
"
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by pjolsen** [comment]
In trying to troubleshoot a bit further (I'm using the code from xPSDesiredStateConfiguration.ps1), it seems to me that the get-group function is failing and returning a $null object silently (due to the try/catch). 

Specifically this line inside the get-group function:
`$group = [System.DirectoryServices.AccountManagement.GroupPrincipal]::FindByIdentity($PrincipalContext, $GroupName)`

This returns the following error:

> format-default : The network path was not found.
>     + CategoryInfo          : NotSpecified: (:) [format-default], COMException
>     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.PowerShell.Commands.FormatDefaultC
>    ommand
> 

The quickest way to replicate this behaviour is the following code:
`add-Type -AssemblyName  System.DirectoryServices.AccountManagement
$ContextType = [System.DirectoryServices.AccountManagement.ContextType]::Machine
[System.DirectoryServices.AccountManagement.GroupPrincipal]::FindByIdentity($ContextType ,"Administrators")`

**Comment by johlju** [comment]
Thanks for the debugging this! I will label this as a bug an help wanted so that someone in the community can run with this.

**Comment by pjolsen** [comment]
Just to confirm - this isn't happening on all systems, so I suspect there's something environmental causing the issue but it would be better if the code could handle the failure gracefully and provide a meaningful error response and not just silently continue.  I have a case open with Microsoft to try to understand why some systems might be responding in this way while others return a group object as expected - if we can discover the issue I will respond here with the findings.

**Comment by johlju** [comment]
@pjolsen I agree, and great that you have a case open!

**Comment by pjolsen** [comment]
We seem to have determined that the network adpater wasn't configured to append the domain suffix for the domain that the objects were members of (we have a root and child domain in the forest). I'm not sure why additions could be made through the GUI but not via the code above. Once we added the the suffixes, it was able to resolve properly. Hope that is helpful for anyone that encounters this issue in the future as it had us scratching our heads for quite some time.

**Comment by johlju** [comment]
@pjolsen many thanks for returning with what caused this. I will close this and label it as external. Thanks for submitting the issue here!
