### ISSUE TITLE
xWindowsOptionalFeature should work on Windows 2012 R2

### ISSUE THREAD

**Issue by ferventcoder** [PowerShell/xPSDesiredStateConfiguration#42]
It's apparently included in Windows 2012 R2, but the check is explicit about client only for the dsc resource (and the built-in resource as well). 

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/f5e56030da118ea10bbec70a890ce7b24602daea/DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.psm1#L256-L259

![image](https://cloud.githubusercontent.com/assets/63502/9616550/5561b326-50c4-11e5-90d9-14409b5f0812.png)

Conversation: https://gitter.im/PowerShell/DscResources?at=55e6137956211cd86f870271

**Comment by iainbrighton** [comment]
This is also needed to enable features on Nano server! I'll put something together..

**Comment by ferventcoder** [comment]
Thanks @iainbrighton
