### ISSUE TITLE
Avoid using the Win32_Product WMI class

### ISSUE THREAD

**Issue by johlju** [PowerShell/xPSDesiredStateConfiguration#422]
This repository has reference to Win32_Product WMI class. As reported in issue https://github.com/PowerShell/DscResources/issues/108, if possible then avoid using the Win32_Product.

>If you are using a group policy with the WMIFilter that queries Win32_Product, modify the filter to use Win32reg_AddRemovePrograms
>...
>Win32reg_AddRemovePrograms is a much lighter and effective way to do this, which avoids the calls to do a resiliency check, especially in a locked down environment. So when using Win32reg_AddRemovePrograms we will not be calling on msiprov.dll and will not be initiating a resiliency check.
>https://support.microsoft.com/en-us/kb/974524

There might not be possible to avoid using it, but for someone to determine that an issue is opened in very repository that has a reference to Win32_Product WMI class.

**Comment by danielboth** [comment]
This one is similar to the issue in PSDscResources, the Win32_Product code is only used in two examples:

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/8ce883237805fd63fe7c7df29cb15aee2b191e91/Examples/Sample_xMsiPackage_InstallPackageFromFile.ps1

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/8ce883237805fd63fe7c7df29cb15aee2b191e91/Examples/Sample_xMsiPackage_UninstallPackageFromFile.ps1

I would say it's fine to close this one @johlju

**Comment by johlju** [comment]
@danielboth Agree, closing this! Thanks!
