### ISSUE TITLE
xRemoteFile re-downloads file every time (request to implement MatchSource property)

### ISSUE THREAD

**Issue by mgr32** [PowerShell/xPSDesiredStateConfiguration#45]
I'm using push mode and need to download a large file from HTTP server. `xRemoteFile` works ok, but it always downloads the file (even if it didn't change), which takes long time to finish. This is because `xRemoteFile` uses local cache and compares LastWriteTime, but the cache is cleared every time I run Start-DscConfiguration.

`MSFT_xRemoteFile.psm1:`
```Powershell
"File" {
            Write-Debug "DestinationPath: '$DestinationPath' is existing file on the machine"

            $file = Get-Item $DestinationPath
            # Getting cache. It's cleared every time user runs Start-DscConfiguration
            $cache = Get-Cache -DestinationPath $DestinationPath -Uri $Uri

            if ($cache -ne $null -and ($cache.LastWriteTime -eq $file.LastWriteTimeUtc))
            {
                Write-Debug "Cache reflects current state. No need for downloading file."
                $fileExists = $true
            }
            else
            {
                Write-Debug "Cache is empty or it doesn't reflect current state. File will be downloaded."
            }              
        }
```

If we're not able to have a persistent cache between Start-DscConfigurations (I'm not sure what are the limitations here), could we possibly add `$MatchSource` parameter (similar to `File` resource) - and when it's $false `Test-TargetResource` would return $true if the file just exists in the destination?

In my use case I'm certain the file will not change on the server as I point to a specific version of the software.

Please let me know your thoughts - I will try to provide a pull request if we're able to agree on approach.

Code to reproduce the issue:

```Powershell
Configuration Test {

    Import-DSCResource -Module xPSDesiredStateConfiguration

    Node localhost { 
        xRemoteFile SolrZip {
            Uri = 'http://apache.mirror.anlx.net/lucene/solr/5.3.1/solr-5.3.1.zip'
            DestinationPath = 'c:\solrtest\solr-5.3.1.zip'
        }
    }
}

Test -OutputPath 'Test'

Start-DscConfiguration -ComputerName localhost -Path 'Test' -Wait -Verbose
```

**Comment by KarolKaczmarek** [comment]
Hi @mgr32 
Cache is being cleared every time Start-DscConfiguration is being run manually, but not when the consistency engine kicks in. So in a usual scenario where you rely on DSC engine to maintain state of your machines, file will not be redownloaded every time.
If that doesn't satisfy your scenario, could you please give more details about it? 
Thanks!

**Comment by mgr32** [comment]
I'm using DSC for deploying an application in push mode (from CI server) - like described in [this blog entry](http://colinsalmcorner.com/post/using-webdeploy-in-vnext-releases) but using [PSCI](https://github.com/ObjectivityBSS/PSCI) ([example](https://github.com/ObjectivityBSS/PSCI/wiki/Getting%20started%20-%20Deploy%20scripts)) instead of TFS Release Management. I need to have control when exactly the application is deployed and want to do it synchronously, plus I want to be able to deploy without any infrastructure changes (no need to setup pull server), thus I'm using push mode.

**Comment by KarolKaczmarek** [comment]
In that case a workaround you could use is to change path where cache for this resource is being stored, line 14:
```
# Path where cache will be stored. It's cleared whenever LCM gets new configuration. 
14 $script:cacheLocation = "$env:ProgramData\Microsoft\Windows\PowerShell\Configuration\BuiltinProvCache\MSFT_xRemoteFile" 
```
If you change it to some custom folder (needs to be outside of the BuiltinProvCache directory), it will not be cleared.

**Comment by mgr32** [comment]
Thanks for the workaround. However, as this doesn't seem to be acceptable final solution, I understand we're not currently able to fix it on the dev branch.

**Comment by KarolKaczmarek** [comment]
I think we should implement the MatchSource property in a similar way to how File resource implements it, however until it's done, the above workaround is the only way to get this scenario working.

**Comment by mgr32** [comment]
Thank you, if that's the case I will try to provide a pull request when time allows :)

**Comment by KarolKaczmarek** [comment]
Thanks! That would be much appreciated.

**Comment by Zuldan** [comment]
I'm having this exact same issue. Some sort of MatchSource would be perfect.

@KarolKaczmarek, the README.md file under xRemoteFile

"Ensure: Ensures that the local file is Present or Absent on the local system", however the Ensure property doesn't exist.

**Comment by KarolKaczmarek** [comment]
@Zuldan It actually have Ensure property, however it's read only:
https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.schema.mof#L10

It's main purpose is to tell you whether file in path specified by DestinationPath is present or not. I agree the name doesn't reflect it's meaning very well, but it's a common pattern among multiple resources to call it ensure, so we left it for consistency. 

I've updated it's description in readme.md to match what's in the schema.mof file.
