### ISSUE TITLE
xWindowsFeature: fails when feature does not exist despite Ensure = Absent

### ISSUE THREAD

**Issue by RobFaie** [PowerShell/xPSDesiredStateConfiguration#452]
#### Details of the scenario you tried and the problem that is occurring
We have DSC in place to make sure SMB1 is not enabled on our 2012R2 servers. We recently had to spin up a new 2012R2 server and is failing the DSC test. The SMB1 feature is no longer included in the 2012R2 image used to create these servers. I agree that the configuration should fail if using Ensure: Present, but with Ensure: Absent the goal of not having the feature enabled is achieved.

#### Verbose logs showing the problem
```
VERBOSE: [NewServer]: LCM:  [ Start  Resource ]  [[xWindowsFeature]SMB1]
VERBOSE: [NewServer]: LCM:  [ Start  Test     ]  [[xWindowsFeature]SMB1]
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Begin executing Test functionality on the FS-SMB1 feature.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_OperatingSystem'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Operation 'Enumerate CimInstances' complete.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Loading module from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ServerManager\ServerManager.psd1'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Loading 'FormatsToProcess' from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ServerManager\Feature.format.ps1xml'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Loading module from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ServerManager\ServerManager.psm1'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Importing cmdlet 'Get-WindowsFeature'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Importing cmdlet 'Install-WindowsFeature'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Importing cmdlet 'Uninstall-WindowsFeature'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Importing function 'Disable-ServerManagerStandardUserRemoting'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Importing function 'Enable-ServerManagerStandardUserRemoting'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Importing alias 'Add-WindowsFeature'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Importing alias 'Remove-WindowsFeature'.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] Querying for feature FS-SMB1 using Server Manager cmdlet Get-WindowsFeature.
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] The operation 'Get-WindowsFeature' started: FS-SMB1
VERBOSE: [NewServer]:                            [[xWindowsFeature]SMB1] The operation 'Get-WindowsFeature' succeeded:
VERBOSE: [NewServer]: LCM:  [ End    Test     ]  [[xWindowsFeature]SMB1] False in 2.2810 seconds.
VERBOSE: [RASGMOV01]: LCM:  [ *FAILED*Test     ]     Completed processing test operation. The operation failed.
PowerShell DSC resource MSFT_xWindowsFeature  failed to execute Test-TargetResource functionality with error message:
System.InvalidOperationException: The requested feature FS-SMB1 could not be found on the target machine.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

#### Suggested solution to the issue
Consider the feature not existing to be compliant for an Ensure: Absent.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
xWindowsFeature SMB1
{
    Ensure = 'Absent'
    Name   = 'FS-SMB1'
}
```

#### The operating system the target node is running
OsName : Microsoft Windows Server 2012 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture : 64-bit
WindowsBuildLabEx : 9200.22570.amd64fre.win8_ldr.180908-0600
OsLanguage : en-US
OsMuiLanguages : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion : 5.1.14409.1012
PSEdition : Desktop
PSCompatibleVersions : 1.0 2.0 3.0 4.0 5.0 5.1.14409.1012
BuildVersion : 10.0.14409.1012
CLRVersion : 4.0.30319.42000
WSManStackVersion : 3.0
PSRemotingProtocolVersion : 2.3
SerializationVersion : 1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
8.4.0.0

**Comment by tmeckel** [comment]
### Analysis

The function `Assert-SingleFeatureExists` seems to be the culprit because it's called in `Test-TargetResource` at https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/9fd047b90f3d74c4a83e0ae0011da1af5b916bbd/DSCResources/MSFT_xWindowsFeature/MSFT_xWindowsFeature.psm1#L391

and throws an exception if the object passed via parameter `-Feature` is `$null`

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/9fd047b90f3d74c4a83e0ae0011da1af5b916bbd/DSCResources/MSFT_xWindowsFeature/MSFT_xWindowsFeature.psm1#L473

### Proposed solution

if the feature can't be found in `Test-TargetResource` and `$Ensure -eq 'Absent'` exit the function and return `$true`to indicate the resource is in it's desired state. A check for installed sub-features isn't necessary if the (parent) feature isn't available for installation.

### Remarks

The corresponding resource `WindowsFeature` in `DscResources` at https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1 shows the same issue and be fixed accordingly.
