### ISSUE TITLE
Why is version 8.5.0.0 not on the gallery

### ISSUE THREAD

**Issue by raandree** [PowerShell/xPSDesiredStateConfiguration#474]
I see that the latest version on GitHub is 8.5.0.0. However, this version hasn't made it to the gallery yet. Is that planned or is something wrong with the latest version?

**Comment by PlagueHO** [comment]
Hi @raandree - this got blocked during release due to test failures. I have a PR through to fix it but just have to make some tweaks for the review to  complete.

**Comment by raandree** [comment]
Thanks for the quick answer!
