### ISSUE TITLE
README.md: Reduce all line lengths to 80 characters or less

### ISSUE THREAD

**Issue by mhendric** [PowerShell/xPSDesiredStateConfiguration#478]
#### Details of the scenario you tried and the problem that is occurring
There are many lines in README.md that are longer than 80 characters. This (among other issues) is preventing opting in to "Common Tests - Validate Markdown Files". README.md should be updated to reduce line lengths.

**Comment by PlagueHO** [comment]
Awesome stuff - totally agree!

**Comment by mhendric** [comment]
I got this one.
