### ISSUE TITLE
README.md: Move change history to dedicated CHANGELOG.md file

### ISSUE THREAD

**Issue by mhendric** [PowerShell/xPSDesiredStateConfiguration#479]
#### Details of the scenario you tried and the problem that is occurring
Just throwing this out for consideration, but it may be good to move the change history out of README.md and into a dedicated CHANGELOG.md file, similar to other DSC resources. This will reduce churn on the README.md itself.

**Comment by PlagueHO** [comment]
100% on board! Gets my vote!

**Comment by mhendric** [comment]
I got this one.
