### ISSUE TITLE
DSC V5 - Keeps attempting to reapply a failed configuraiton

### ISSUE THREAD

**Issue by AlexisColes** [PowerShell/xPSDesiredStateConfiguration#49]
We have started using DSC to deploy some applications. We are pushing out the configurations and only want it to run this configuration once and then stop. However it seems that if a configuration fails we end up with a pending configuration which DSC seems to keep attempting to reapply. Is this intended behavior? Is there anyway for us to prevent this happening.

Here are our LCM settings

ActionAfterReboot              : ContinueConfiguration
AgentId                        : 4314CBF5-928E-11E5-941E-00155D0****
AllowModuleOverWrite           : True
CertificateID                  : EBB297F164BDA1C1A7918C12C31D0F70110****
ConfigurationDownloadManagers  : {[ConfigurationRepositoryWeb]DSCHTTP}
ConfigurationID                : 3fa96bab-ac50-4b80-a9ac-384bfd*****
ConfigurationMode              : ApplyOnly
ConfigurationModeFrequencyMins : 15
Credential                     : 
DebugMode                      : {NONE}
DownloadManagerCustomData      : 
DownloadManagerName            : 
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : Idle
LCMStateDetail                 : 
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
PartialConfigurations          : 
RebootNodeIfNeeded             : True
RefreshFrequencyMins           : 30
RefreshMode                    : Push
ReportManagers                 : {}
ResourceModuleManagers         : {[ResourceRepositoryWeb]DSCHTTP}
PSComputerName                 : D6B*****01
PSComputerName                 : D6B*****01

**Comment by iainbrighton** [comment]
HI @AlexisColes - As far as I'm aware this is intended behaviour. By using DSC to configure the node you have said you WANT that configuration and it will attempt to configure the node until it's configured appropriately.

You should be able to remove the pending configuration from the node with `Remove-DscConfigurationDocument -Stage Pending`, but that doesn't solve your real problem..

**Comment by AlexisColes** [comment]
Thanks for your response @iainbrighton .  I know the problem is the desired state configuration we are running is not really the desired state, more like a base desired state.

In order to fix the real problem we need to artifact all our builds, tag the correct versions of our artifacts into a release, then tag the environment with that release version and get it to dynamically generate a mof file with the correct versions of all our artifacts for each environment.  Once all this is done and we are running a real desired state configuration, you are right it matters little if it keeps plugging away at it.
However for now this is out of reach :(, maybe one day. 

We have tried catching failed DSC runs and running  Remove-DscConfigurationDocument -Stage Pending however it does not seem to work all the time, some bug in our script somewhere I suppose, it is on the list to look into.

Was just hoping there was a way of changing this behavior with the platform.
