### ISSUE TITLE
xPackage CreateCheckRegValue when key is not a string

### ISSUE THREAD

**Issue by wasabii** [PowerShell/xPSDesiredStateConfiguration#51]
I'm trying to install .Net 4.6.1, which requires me to set SOFTWARE\Microsoft\NET Framework Setup\v4\Full:Release to a given numerical value in order for xPackage to work. The installer does not set this flag until the reboot. And xPackage fails to consider the package as successfully installed if the value is not set. So I intend to have it set by xPackage, so that it considers it installed.

However, this is a DWORD, not a string. So setting it results in a failure.

**Comment by pieterv-icloud-com** [comment]
How did you resolved the DWORD issue?

Currently facing the same issue.
