### ISSUE TITLE
RegisterDscAgentUnsuccessful Forbidden

### ISSUE THREAD

**Issue by SteveKeller** [PowerShell/xPSDesiredStateConfiguration#512]
### When register a DSC agent to the pull server error message forbidden appears.

- Already checked the RegistrationKey (client and pull server) -> are matching 
- connection to pull server from client ok
- client certificate in the windows cert store for the pull server valid
- other maschine's using same pull server are ok
- deleted DSC MOF's in C:\Windows\System32\Configuration -> no impact
- new agent id generated -> no impact

#### Details of the scenario you tried and the problem that is occurring
Problem occurs when apply local MOF File with following command (in elevated command promt).

`Set-DscLocalConfigurationManager -Path LCM -Verbose`

#### Verbose logs showing the problem

```
Registration of the Dsc Agent with the server https://dscpull.mydomain.com:8080/PSDSCPullServer.svc failed. The underlying error is: The attempt to 
register Dsc Agent with AgentId FCD53DF6-XXXX-XXXX-XXXX-XXXXXXXXXXXX with the server 
https://dscpull.mydomain.com:8080/PSDSCPullServer.svc/Nodes(AgentId='FCD53DF6-XXXX-XXXX-XXXX-XXXXXXXXXXXX') returned unexpected response code 
Forbidden. 
    + CategoryInfo          : InvalidResult: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : RegisterDscAgentUnsuccessful,Microsoft.PowerShell.DesiredStateConfiguration.Commands.RegisterDscAgentCommand
    + PSComputerName        : localhost
```

#### Windows Error Log
**EventID:** 4252
**MessageID:** RegisterDscAgentUnsuccessful,Microsoft.PowerShell.DesiredStateConfiguration.Commands.RegisterDscAgentCommand
**ErrorCategory:** 8
**ErrorCode:** 1
**ErrorType:** MI

#### The operating system 
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2608.amd64fre.rs1_release.181024-1742
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell 
PSVersion                      5.1.14393.2608                                                                                                          
PSEdition                      Desktop                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                 
BuildVersion                   10.0.14393.2608                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                         
WSManStackVersion              3.0                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                     
SerializationVersion           1.1.0.1

#### Version of the DSC module
xPSDesiredStateConfiguration_5.0.0.0

Any ideas to solve the problem?

**Comment by mhendric** [comment]
It doesn't look like this error is coming from this module, but rather from PowerShell or from Windows itself. I searched both this repository and the (powershell repository)[github.com/powershell/powershell], but can't find error RegisterDscAgentUnsuccessful anywhere. Does anyone know who owns the module responsible for this (Microsoft.PowerShell.DesiredStateConfiguration.Commands.RegisterDscAgentCommand)? That may be a good place to ask for help too if no one here can figure it out.

That being said, 'Forbidden' sounds like it's possibly an IIS error. You may want to check the IIS and HTTPERR logs if you haven't already.

**Comment by mhendric** [comment]
Also, xPSDesiredStateConfiguration_5.0.0.0 is 2 years old if that is in fact what you're using. Y may want to get the latest module version (8.4.0.0) at https://www.powershellgallery.com/packages/xPSDesiredStateConfiguration and then try again.

**Comment by SteveKeller** [comment]
I have nothing seen in the IIS Logs and still can not solve the forbidden error.
This is a valuable tip with the outdated module, thanks!

I will try to update the module, but it takes some time :)

Thanks a lot for your input!
