### ISSUE TITLE
xPSDesiredStateConfiguration: Support for PowerShell 4

### ISSUE THREAD

**Issue by mhendric** [PowerShell/xPSDesiredStateConfiguration#522]
We don't currently have any automated tests that test this module using PowerShell 4. It's also starting to look like parts of the module don't currently work with PowerShell 4 (see #511). I think we need to figure out what our stance is on PowerShell 4 going forward. Do we want to fully support it? If so, I think we need to get PowerShell 4 based test coverage on it. Do we want to drop official support for it? Do we take the stance that this MAY work with PowerShell 4, but we're not going to test it? Open to other suggestions, but wanted to at least start a discussion on the topic.

**Comment by PlagueHO** [comment]
A good question. Let's bring it up at the community call. I'm assembling a list of things to bring up.

**Comment by tmeckel** [comment]
Normally you'd ditch this module because Powershell 4 is now so damn outdated. But I would believe there 're still many PS4 installations out there in the wild :-D

**Comment by tmeckel** [comment]
One addtion https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/511#issuecomment-460194610 .. We can't simply ditch xPSDesiredStateConfiguration because it conatins unique DSC Modules like MSFT_xDSCWebService.psm1

**Comment by tmeckel** [comment]
@mhendric , @PlagueHO so after the last community call and the explanations from @kwirkykat  .. can this issue be closed now? I would prefer though, this issue is not simply closed but that some statements are added to the README.md files in the two repositories respectively that reflect the statements from Katie.

**Comment by mhendric** [comment]
Yeah, I think we just need to add a formal statement at the top of the README.md on our PS4 stance, then this can be closed. Perhaps something like this. What do you all think?

This module is automatically tested using PowerShell 5.1 on servers running Windows 2012 R2 and Windows 2016, and is expected to work on other operating systems running PowerShell 5.1. While this module may work with PowerShell versions going back to PowerShell 4, there is no automatic testing performed for these versions, and thus no guarantee that the module will work as expected.

**Comment by PlagueHO** [comment]
That looks pretty good @mhendric

**Comment by tmeckel** [comment]
Yes I agree with @PlagueHO ... sounds great!
