### ISSUE TITLE
xArchive does not allow $Checksum to be specified.

### ISSUE THREAD

**Issue by CtrlC-Root** [PowerShell/xPSDesiredStateConfiguration#53]
So as far as I can tell there's no way to specify the checksum xArchive should use when comparing two files. I believe the default value results in comparing file names which is inadequate for all of my use cases. It looks like the functionality to use alternate algorithms is already implemented just not broken out using any resource parameter.

**Comment by kwirkykat** [comment]
There is a Checksum parameter on xArchive now
