### ISSUE TITLE
DSCPullServerSetup/PublishModulesAndMofsToPullServer.psm1: Fix Style Inconsistencies

### ISSUE THREAD

**Issue by mhendric** [PowerShell/xPSDesiredStateConfiguration#530]
#### Details of the scenario you tried and the problem that is occurring
DSCPullServerSetup/PublishModulesAndMofsToPullServer.psm1 has a number of style inconsistencies that need to be cleaned up to align with DSC style guidelines.

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by tmeckel** [comment]
Perhaps we can motivate @Duffney (https://github.com/Duffney) to work on this ;-)
