### ISSUE TITLE
Fix Remaining PSScriptAnalyzer Violations

### ISSUE THREAD

**Issue by mhendric** [PowerShell/xPSDesiredStateConfiguration#546]
The following PSScriptAnalyzer violations need to be cleaned up as part of the effort to make this a Hiqh Quality Module:

Updated 3/22/2019
```
PS C:\>         $ignorePssaRuleNames = @(
>>             'PSDSCDscExamplesPresent',
>>             'PSDSCDscTestsPresent',
>>             'PSUseBOMForUnicodeEncodedFile',
>>             'PSUseShouldProcessForStateChangingFunctions',
>>             'PSUseSingularNouns',
>>             'PSUseToExportFieldsInManifest',
>>             'PSUseUTF8EncodingForHelpFile'
>>         )
PS C:\> $results = Invoke-ScriptAnalyzer -Path 'C:\Program Files\WindowsPowerShell\Modules\xPSDesiredStateConfiguration' -Recurse -ExcludeRule $ignorePssaRuleNames
PS C:\> $results | group-object RuleName | sort-object count -Descending | ft Count,Name

Count Name                                          
----- ----                                          
   55 PSUseDeclaredVarsMoreThanAssignments          
   27 PSAvoidGlobalVars                             
    6 PSUseOutputTypeCorrectly                      
    4 PSAvoidUsingConvertToSecureStringWithPlainText
    2 PSPossibleIncorrectComparisonWithNull         
    1 PSAvoidDefaultValueForMandatoryParameter      
    1 PSAvoidUsingInvokeExpression                  



PS C:\> $results | group-object ScriptName | sort-object count -Descending | ft Count,Name

Count Name                                         
----- ----                                         
   25 MSFT_xRemoteFile.Tests.ps1                   
   16 MSFT_xEnvironmentResource.EndToEnd.Tests.ps1 
    9 MSFT_xArchive.TestHelper.psm1                
    6 MSFT_xGroupResource.Tests.ps1                
    5 PullServerSetupTests.ps1                     
    4 MSFT_xArchive.Tests.ps1                      
    4 MSFT_xArchive.Integration.Tests.ps1          
    4 CommonResourceHelper.Tests.ps1               
    3 MSFT_xEnvironmentResource.Tests.ps1          
    3 MSFT_xWindowsPackageCab.Integration.Tests.ps1
    3 MSFT_xWindowsFeature.Integration.Tests.ps1   
    2 PublishModulesAndMofsToPullServer.psm1       
    2 MSFT_xPackageResource.Integration.Tests.ps1  
    2 MSFT_xWindowsProcess.Tests.ps1               
    1 MSFT_xDSCWebService.config.ps1               
    1 MSFT_xPackageResource.TestHelper.psm1        
    1 MSFT_xGroupResource.TestHelper.psm1          
    1 xFileUpload.schema.psm1                      
    1 MSFT_xMsiPackage.Tests.ps1                   
    1 MSFT_xRegistryResource.Tests.ps1             
    1 MSFT_xScriptResource.Tests.ps1               
    1 MSFT_xWindowsOptionalFeature.Tests.ps1  
```

**Comment by mhendric** [comment]
I'll take this.

**Comment by mhendric** [comment]
Closing this. I plan to open a new issue with fixes required for individual files.

**Comment by mhendric** [comment]
Question for the community. How do we want to address the PSUseShouldProcessForStateChangingFunctions violations? DSC doesn't support ShouldProcess, so I don't see much benefit in adding ShouldProcess support. So that leaves either suppressing this rule to cleanup the PSScriptAnalyzer output, or just ignoring this rule altogether. Thoughts?

**Comment by PlagueHO** [comment]
I don't think we should be adding ShouldProcess support. We don't actually suppress PSUseShouldProcessForStateChangingFunctions because it is not included in the list of rules we apply to DSC (see: https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/.vscode/analyzersettings.psd1).

You could run the PSSA above again, but just use the DSC rules list and that might cut the number down - and also identify the custom violations as well.

**Comment by mhendric** [comment]
> You could run the PSSA above again, but just use the DSC rules list and that might cut the number down - and also identify the custom violations as well.

Good idea. What's the syntax I would use for that?

**Comment by mhendric** [comment]
Nevermind. Figured it out. Inventory updated.

**Comment by mhendric** [comment]
@PlagueHO , I'm working on a PR for the last two script analyzer categories. Once these are all fixed, I'm wondering if we should make some of these mandatory so that they're flagged in the future. Rules like PSAvoidTrailingWhitespace for instance. What do you think, and if you agree, what's the best way to handle this? Just add them to the appveyor.yml?

**Comment by PlagueHO** [comment]
@mhendric - I'm in support of adding these. We'd want to do it in the AppVeyor.psm1 though as a new optin (not the .yml). That way other repos could opt in as well (I'd like to :grin:)
