### ISSUE TITLE
Enable Rolling Builds in AppVeyor?

### ISSUE THREAD

**Issue by mhendric** [PowerShell/xPSDesiredStateConfiguration#569]
I wanted to see what everyone thinks about enabling [Rolling Builds](https://www.appveyor.com/docs/build-configuration/#rolling-builds) for this project? And does anyone know who has permissions to do this in the AppVeyor settings for the project? I've been noticing lots of queued build jobs lately with all the work going on in this module, and often the active jobs are old commits for a PR where the jobs for newer commits are queued. I think it may be better to have new commits for a PR just cancel any active builds for old commits on the same PR, since we generally only care about the test results of the latest commit.

**Comment by mhendric** [comment]
@mgreenegit  , do you know who has access to the AppVeyor project and can make this change? I'd like to make this if no one in the community has objections. Tagging @PlagueHO and @johlju for comment too.

**Comment by johlju** [comment]
It is @keirkykat that has enough power in AppVeyor to make that change. 

It sounds like this “rolling builds” should be the default for all repos in DSC Resource Kit to lessen the load on the PowerShell AppVeyor account. 

More info about rolling builds https://www.appveyor.com/docs/build-configuration/#rolling-builds.

**Comment by johlju** [comment]
@gaelcolas maybe you can look into this when you get permission in DSC Resource Kit?

**Comment by gaelcolas** [comment]
On my radar. It should happen soon, I'm told.

**Comment by mhendric** [comment]
> It sounds like this “rolling builds” should be the default for all repos in DSC Resource Kit to lessen the load on the PowerShell AppVeyor account.

I agree. Or at least on the repo's I help maintain :) . @gaelcolas , can you do this for xExchange and xBitlocker too? I can open Issues in those repos if it will help too. Just let me know.

**Comment by mgreenegit** [comment]
I see no reason not to do this.  @mhendric, enabling for all three of the projects you maintain.  @gaelcolas and @kwirkykat, fyi
![image](https://user-images.githubusercontent.com/5178939/53970092-9983e580-40bf-11e9-8c67-cb5bbf924038.png)

**Comment by mhendric** [comment]
Sweet. Thanks @mgreenegit !
