### ISSUE TITLE
CHANGELOG.MD: Move update responsibility to repo maintainers?

### ISSUE THREAD

**Issue by mhendric** [PowerShell/xPSDesiredStateConfiguration#592]
I'm sure this has been discussed elsewhere previously, but I wanted to see what people think about changing the repo responsibilities so that the repo maintainers have to update the CHANGELOG.MD, not the people submitting Pull Requests. We often get in a situation where a handful of PR's have been approved via code review, but only one can be merged at a time since the changes from one merge cause the other PR's to require a rebase. I propose changing the requirements so that the person submitting the PR must put a detailed change entry in the PR itself, but all changes to the CHANGELOG would be done by maintainers, in separate Pull Requests. Thoughts?

**Comment by mhendric** [comment]
Tagging @PlagueHO as the co-maintainer of this module. And also @johlju since he maintains a number of modules himself.

**Comment by PlagueHO** [comment]
I missed this one and actually commented on this elsewhere.

If you add the each change just under the # Unreleased header then this issue dosesn't occur as often because git can usually fast-foward changes like that.

This actually makes more sense from a chronological perspective (but not at first) - because you'd expect older changes to be closer to the bottom of the file while the most recent changes to be at the top.

**Comment by mhendric** [comment]
Ok. Maybe we should update the Pull Request template then to say that the changelog entry must go directly underneath the Unreleased section?

**Comment by PlagueHO** [comment]
We'd probably also need to update the contribution document as well. Might be worth raising this issue over in DSCResources repo instead?

**Comment by mhendric** [comment]
Sounds good. Also, just for my understanding, are you saying putting entries directly under "Unreleased" would eliminate the need for a rebase, or would eliminate merge conflicts when doing a rebase? My intention here is to eliminate the need for a rebase, not just to make rebasing easier.

**Comment by PlagueHO** [comment]
It should eliminate the need for the rebase I think because Git will be able to automatically update without a merge conflict. I could be wrong though.

**Comment by mhendric** [comment]
Right, but it still causes the Pull Request to have to go through Continuous Integration again, which adds another hour before it can be merged. And that's if there aren't other Pull Requests in a similar state, in which case you'll wait a minimum of an hour for each PR. I would like to eliminate this 'Pull Request Queuing' where we keep having to do new commits, and as a result, new tests, just to keep the change log up to date.

Also, don't you have to manually hit the Update button to begin the auto merge?

**Comment by PlagueHO** [comment]
You do have to hit the update button. But I think the reality is that we're always going to need a process to do that. Fundamentally the CI must run against the "merged" branch prior to performing the merge. Otherwise we'd likely end up with broken builds in Dev more often.

Perhaps there is an option in AppVeyor to terminate CI runs when a newer commit is present? This is an option in Azure DevOps. This would eliminate some queues.

Although, in reality we're not going to have quite the volume of PR's going through this repo once we've finished cleaning it up. Or at least I'd assume we won't.

**Comment by mhendric** [comment]
Yeah again, the problem I have isn't really with needing to hit an update button. It's just that we're forcing additional hours upon PR's that are otherwise ready to merge, just because of changed code in a file those PR's weren't even necessarily trying to fix in the first place. I think it would be better if the Pull Requester only ever had to do rebases on files they were specifically updating, and the maintainers could keep the change log up to date separately.

Not sure if it's possible, but with the changes @johlju made recently, we also might be able to configure Appveyor.yml to only execute the Meta tests (and skip the Unit and Integration tests) when a PR that only modified the .MD files was made. That would make it a lot quicker for a maintainer to keep the changelog up to date.

I agree that PR's may not always be queuing like this, but I think any streamlining we can do of the process is a win. Especially when in repos that take 40+ minutes to runs all tests.

Another benefit of having maintainers keep the change log up to date would be that it would be easier to keep a consistent format throughout the file.

> Perhaps there is an option in AppVeyor to terminate CI runs when a newer commit is present? This is an option in Azure DevOps. This would eliminate some queues.

That was just addressed in #569 so I think we're good there.

**Comment by PlagueHO** [comment]
I think I'd rather avoid having to keep the CHANGELOG up-to-date myself for every change as we'd still need to track change in DEV somehow - someplace. I'd love consistency with the CHANGELOG.MD but from what I've seen there isn't any consistency across repos anyway - even with the instructions we provide.

I'd also worry that if a maintainer wasn't around to update the CHANGELOG.MD prior to monthly release then the module would get omitted or worse, released without an updated CHANGELOG.MD.

The thing I try to consider when thinking about changes like this is that it affects 10s of repos and incurs a lot of change across the board - which is most likely not going to get picked up everywhere.

**Comment by mhendric** [comment]
Not sure if it's possible, but what about if we could configure Appveyor.yml to perform this sort of logic:

-If the immediately prior commit for this PR has run and passed all required tests
-And if the current commit is only modifying a .MD file
-Then only run Meta tests

Would you be open to that? That would speed up the process as well.

**Comment by johlju** [comment]
I rather not update the change log monthly, that would just be to much work. If we do something like this, we should update release notes and use the GitHub releases instead somehow (automatic). Not possible I think.
I don't see this as a big problem. 🙂 I usually wait until next day and merge next PR if i could resolve the conflicts for the contributor (and let the tests run).  

> And if the current commit is only modifying a .MD file

 You can add a 'skip CI' in a commit message and the entire CI is skipped. There is some control around skipping CI on certain files, but I think then they are always skipped.

The logic you suggest above must be coded I think.

**Comment by mhendric** [comment]
Sounds like I'm the only one that thinks this is a good idea, so I'll go ahead and close out for now.
