### ISSUE TITLE
SQL Database fails do to typo in source

### ISSUE THREAD

**Issue by Fiander** [PowerShell/xPSDesiredStateConfiguration#631]
Hi,
in xPSDesiredStateConfiguration/DSCResources/MSFT_xDSCWebService/

on row 464 there is a typo.

  if ($SqlProvider)
    {
        Write-Verbose -Message 'Set values into the web.config that define the SQL Connection'
        PSWSIISEndpoint\Set-AppSettingsInWebconfig -Path $PhysicalPath -Key 'dbprovider' -Value $jet4provider
        PSWSIISEndpoint\Set-AppSettingsInWebconfig -Path $PhysicalPath -Key **'dbconnectionst'** -Value $SqlConnectionString
        if ($isBlue)
        {
            Set-BindingRedirectSettingInWebConfig -Path $PhysicalPath
        }
    }
    elseif ($isBlue)
    {
        Write-Verbose -Message 'Set values into the web.config that define the repository for BLUE OS'
        PSWSIISEndpoint\Set-AppSettingsInWebconfig -Path $PhysicalPath -Key 'dbprovider' -Value $eseprovider
        PSWSIISEndpoint\Set-AppSettingsInWebconfig -Path $PhysicalPath -Key **'dbconnectionstr'** -Value $esedatabase
        Set-BindingRedirectSettingInWebConfig -Path $PhysicalPath
    }

There seems to be missing a "r"

**Comment by mhendric** [comment]
Looks like a bug to me. @johlju , I think you're a SQL guru, do you concur?

**Comment by mhendric** [comment]
Also, @Fiander , do you have a way to reproduce a problem caused by this typo? Or any error messages caused by the typo?

**Comment by johlju** [comment]
@mhendric that is application specific. The web application read the connection string from the web.config. So the web application is gonna look for a specific string is my guess. So the correct key could be ‘dbconnectionst’, ‘dbconnectionstr’, or ‘dbconnectionstring’ or something else :)

Would be great to see an error message to see if the actual key is written in the error message. 
Or it’s trial an error to see what key name will make it work :)

Did this change in a recent merge or has this was an issue a while?

**Comment by Fiander** [comment]
the problem i was having was that while installing a pull server with a sql backend, the database never gets created, and in the web config the key "dbconnectionst " is present.

when doing refresh of the setup of the pull server, DSC sees that the db string is not correct and tries to fix it. 

by changing the web.config and changeing the key to "dbconnectionstr" the database gets created, and DSC finds the key to be correct.

**Comment by mhendric** [comment]
Confirmed that this was in fact changed (and then broken) by this commit:

https://github.com/PowerShell/xPSDesiredStateConfiguration/commit/03c1d58eed03bd2359b34cd6ee433a007645c730#diff-fbf44002358de666e2c0e2f4e2fca2c9
