### ISSUE TITLE
xService does not update the binary path.

### ISSUE THREAD

**Issue by CtrlC-Root** [PowerShell/xPSDesiredStateConfiguration#72]
The `xService` module does not update the installed service if the `Path` parameter changes. This is inconvenient because if it changes you have to first remove the service and then re-add it. Since the `Name` parameter is required for both operations and it's a key you can't do this in a single DSC configuration block.

My thought is the resource should check if the path needs to be updated and if it does re-install the service with the correct path. I'm operating under the assumption that it can't be updated once the service has been created, but my knowledge in this area is limited so feel free to correct me if I'm wrong. I'd be willing to implement this in a pull request if I can get some feedback from the repository owners on whether they'd like to see this functionality included in the module.

**Comment by kwirkykat** [comment]
Closed in #73
