### ISSUE TITLE
xService does not add log on as service

### ISSUE THREAD

**Issue by AceHack** [PowerShell/xPSDesiredStateConfiguration#76]
Hope this gets fixed soon.  Thanks.

**Comment by PlagueHO** [comment]
I think this was resolved with #216. @AceHack  - are you able to confirm the fix works for you if you get a chance? You'd need to use the Dev branch until this is released via PS Gallery or the Resource Kit.

**Comment by johlju** [comment]
Closing this as resolved as per previous comment. If this was closed in error please reopen or comment.
