### ISSUE TITLE
Desired state configuration life time (dispose)

### ISSUE THREAD

**Issue by AlexisColes** [PowerShell/xPSDesiredStateConfiguration#77]
This is more of a feature request rather than a issue, this is the best place I could find to make it, hope this is ok.

I am not sure what the lifetime of a DscResource class is but could it be for the lifetime of 1 run and contain a dispose method.

I am looking to write some configuration transformation logic into dsc resource.  The basic plan of attack is to run a transformation process against some source configuration files and write the result to a temporary folder.  The test process would then be to compare these files to the deployed files and ensure they match.  It would be nice if the set method could then check to see if these files have been created and if so just copy them to the right location.  It seems like a senseless overhead to have to regenerate these for the set method if they have already been generated for the test method.

If we could have a dispose method that run at the end of the run against all the resources we could then get our access point to clean up these temporary files regardless of whatever combination of test and set have been called.

**Comment by kwirkykat** [comment]
You should open this as an issue in [UserVoice for PowerShell DSC](https://windowsserver.uservoice.com/forums/301869-powershell/category/148047-desired-state-configuration-dsc).
