### ISSUE TITLE
xGroup Please create a Name key property

### ISSUE THREAD

**Issue by AceHack** [PowerShell/xPSDesiredStateConfiguration#78]
I don't want this do anything other than let me make this unique.  Right now I'm hitting a bug that produces the following error.  This is not xGroup itself causing the bug, I believe it's a MOF generation issue.  I've had this exact same problem with my own Resources and solved it by added a completely unused Name key that will just allow me to make it unique.

The WS-Management service cannot process the request. The WMI service or the WMI provider returned an unknown error: HRESULT 0x80041033 
At C:\Code\Itron Analytics - Smart Grid\dev\PerformanceManager\PowerShell\Scripts\PmFarmConfiguration.ps1:256 char:9
+         Start-DscConfiguration -Force -Verbose -Wait -Path $workingFo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041033
    + PSComputerName        : localhost

**Comment by iainbrighton** [comment]
@AceHack The `GroupName` property is currently the key. Why would adding another `Name` key help in your instance?

**Comment by kwirkykat** [comment]
The GroupName property is the unique key for xGroup.
