### ISSUE TITLE
Move integration test for xDSCWebservice resource.

### ISSUE THREAD

**Issue by BerheAbrha** [PowerShell/xPSDesiredStateConfiguration#83]
There are set of tests under xPSDesiredStateConfiguration\Examples\ which validate pull server deployment. This issue is to make those test part of an integration test so that future change to the resource will be validated.

**Comment by kwirkykat** [comment]
These will get moved as part of #160

**Comment by BerheAbrha** [comment]
@kwirkykat  As part of #160, is there a plan to also setup a pull server using the resource and do basic pull server testing with it ? if there is I can close this one as duplicate.

**Comment by kwirkykat** [comment]
@BerheAbrha I'm not sure yet if we will be able to set up a pull server using AppVeyor without revealing secrets (password, keys, etc.), so I would leave this open for now.

**Comment by kwirkykat** [comment]
These tests were moved to the DSCPullServerSetup folder in #318
