### ISSUE TITLE
ReportServerWeb

### ISSUE THREAD

**Issue by ArieHein** [PowerShell/xPSDesiredStateConfiguration#96]
per :  https://msdn.microsoft.com/en-us/powershell/dsc/reportserver

        ConfigurationRepositoryWeb CONTOSO-PullSrv
        {
            ServerURL = 'https://CONTOSO-PullSrv:8080/PSDSCPullServer.svc'
            RegistrationKey = 'fbc6ef09-ad98-4aad-a062-92b0e0327562'
        }

        ReportServerWeb CONTOSO-PullSrv
        {
            ServerURL = 'https://CONTOSO-PullSrv:8080/PSDSCPullServer.svc'
        }

When using a Pull Server v5 and using RegistrationKey method.
If i intend the pull server to be the configuration and report server, why do i need to add a ReportServerWeb block that merely states again the the address, same as the ConfigurationRepositryWeb? Shouldnt that be the default ? 

Are there any cases where people would have one pull server and would not want reporting builtin ?

per : https://msdn.microsoft.com/en-us/powershell/dsc/pullserver
the sample shows a report server pointing to the same pull server, but this time it does state the RegistrationKey. So which is it? do you have the state the RegistrationKey for the ReportServerWeb or not in this case ?

What happens then with ResourceRepositoryWeb ?
Do i need to specificaly add a block pointing again just to the same ServerURL of the Pull Server with no additional settings ? or in this case its the default behaviour  that if you dont state the  ResourceRepositoryWeb  block its assumed it comes from the pull server section ? If thats the case why the difference in behaviour between ReportServerWeb and ResourceRepositoryWeb  ?

**Comment by NarineM** [comment]
@ArieHein , 
Reporting server stores detailed information about node configuration run status not only for pull but also for push operations. One can setup a node in push mode using a meta configuration with just ReportServerWeb and no ConfigurationRepositoryWeb block. By default (and if no ReportServerWeb is specified in meta configuration) the reporting is turned off.
When the reporting is turned on a given node, it will report the status from DSC operations to the reporting server. If the node is setup to pull configurations for example from a web repository(ConfigurationRepositoryWeb case) and also reporting is turned on,  it will report status from configuration( downloaded from a given repository) runs to the server using the reporting serverURL specified in ReportServerWeb block .
ConfigurationRepositoryWeb, ResourceRepositoryWeb , etc are the ways to specify repositories or additional repositories for downloading configurations or resources from  when ReportServerWeb is about specifying where to the node should send its status reports to. So these servers do not have to be (but they can) be the same endpoint.
